#!/bin/csh -f
#
# testa all programs with oc8051 microcontroler
#

set failedi = 0;
set failedx = 0;
set all_testsi = 0;
set all_testsx = 0;

set internal_tests=(fib divmul sort gcd cast xram)

set external_tests=(fib divmul sort gcd cast xram)

echo " Compiling with VCS "
	    
vcs +v2k -Mupdate +vcs+lic+wait -I -notice +libext+.v +define+NOTIMINGCHECKS +define+NOCOPYRIGHT -full64 -P /tools/novas/Novas-200704/share/PLI/vcsd2006.06/LINUX64/vcsd.tab /tools/novas/Novas-200704/share/PLI/vcsd2006.06/LINUX64/pli.a -f filelist_top.f > ../log/complie.log


if ($status != 0) then
  echo "#### Compile : FAILED"
  echo ""
  cat ../log/complie.log
  exit
else
  echo "#### Compile : PASSED"
endif

# Run the NC-Verilog simulator (simulate the design)

echo ""
echo "###########################################"
echo " Tesing programs from internal rom"
echo "###########################################"

\cp -rf ./dat/oc8051_eai.in ./dat/oc8051_ea.in
set i = 0;
        echo "###########################################"
foreach internal_test ($internal_tests)
	@ i += 1;
	#echo ""
	#echo "### Running test ${i}: ${internal_test}"

	\cp ../tests/dat/${internal_test}.dat ./dat/oc8051_xrom.in
	simv +DUMP  > ../log/run.log
	if ($status != 0) then
	  cat ../log/run.log
	  exit
	else if (`tail -100 ../log/run.log | grep Passed` == "") then
	  echo "### test ${i}: ${internal_test} --> FAILED"
          @ failedi += 1;
          @ all_testsi += 1;
        else
	  echo "### test ${i}: ${internal_test} --> PASSED"
          @ all_testsi += 1;
	endif
  mv ../log/run.log ../log/${internal_test}.log


end
    echo "###########################################"

echo ""
echo ""
echo "###########################################"
echo "### tesing programs from external rom"
echo "###########################################"

\cp -rf ./dat/oc8051_eax.in ./dat/oc8051_ea.in
set i = 0;
        echo "###########################################"
foreach external_test ($external_tests)
	@ i += 1;
	#echo ""

	\cp ../tests/dat/${external_test}.dat ./dat/oc8051_xrom.in
	simv +DUMP -NOCOPYRIGHT -f filelist_top.f > ../log/run.log
	if ($status != 0) then
	  cat ../log/run.log
	  exit
	else if (`tail -100 ../log/run.log | grep Passed` == "") then
	  echo "### test ${i}: ${external_test} --> FAILED"
          @ failedx += 1;
          @ all_testsx += 1;
        else
	  echo "### test ${i}: ${external_test} --> PASSED"
          @ all_testsx += 1;
	endif
  mv ../log/run.log ../log/x_${external_test}.log

end
        echo "###########################################"

echo ""
echo "###########################################"
echo "###  Test Summary                          "
echo "### "
echo "### Failed $failedi of $all_testsi internal tests"
echo "### Failed $failedx of $all_testsx external tests"
echo "###########################################"


