

# Inherit global environment

import os, sys

PROJRELROOT = '../../../'

sys.path.append(PROJRELROOT)

from config.projpaths import *
from configure import *

Import('env', 'platform', 'symbols')

# The set of source files associated with this SConscript file.
src_local = ['platform.c', 'irq.c']
obj = env.Object(src_local)

# This is arealview platform, include corresponding files.
obj += SConscript(join(PROJROOT, 'src/platform/realview/SConscript'), exports = {'env' : env, 'symbols' : symbols},
		duplicate=0, build_dir='realview')

Return('obj')
