#!/bin/sh -f

# remove old run file
rm -rf ./run_alu

if [ ! -n "$1" ]; then
  EXTRA_OPTS=""
else
  EXTRA_OPTS="$*"
fi

if [ ! -n "$BARREL_SHIFTER" ]; then
  BARREL_SHIFTER="$ALU_COMPONENTS/barrel_shifter/simple/barrel_shifter_simple.v"
fi

if [ ! -n "$ADDER" ]; then
  ADDER="$ALU_COMPONENTS/adder/alu_adder.v"
fi

INCDIR="-I $ALU_RTL"

echo Using iverilog options $EXTRA_OPTS
cmd="iverilog ${EXTRA_OPTS} $INCDIR $ADDER $BARREL_SHIFTER $ALU_RTL/alu_datapath.v $ALU_RTL/alu_controller.v $ALU_RTL/alu.v $ALU_BASE/tb/alu_tb.v -o run_alu"
echo $cmd
$cmd
./run_alu
