#    This file is part of gasm.
#
#    
# If you encountered any problem, please contact :
#                                                 
#   lmouton@enserg.fr                             
#   shangoue@enserg.fr                            
#                                                 



# Définition des dépendances

dialogue_DEP =
formateur_DEP = dialogue
parametres_DEP = formateur
preprocesseur_DEP = dialogue formateur parametres
adaptateur_DEP = dialogue formateur parametres preprocesseur
preparateur_DEP = dialogue formateur parametres adaptateur
analyseur_DEP = dialogue formateur parametres preprocesseur adaptateur preparateur
synthetiseur_DEP = dialogue formateur parametres adaptateur analyseur

ALL = dialogue formateur parametres preprocesseur adaptateur preparateur analyseur synthetiseur
