#!/bin/sh
for x in 0 1 2 3 ; do
    for y in 0 1 2 3; do 
        echo "cpu0${x}_0$y.c"
	rm	cpu0$x_$y.c
	cp cpu.c	 "cpu0${x}_0$y.c"
    done
done
	
          # echo item: cpu0$x$y.c
	    #cp cpu00_001.c	cpu0$x_$y.c
	#done
	

