#!/bin/sh
# $Id: makerom,v 1.2 2006-12-29 08:17:17 sybreon Exp $
#
gpasm -c -o rom $1 && gplink -o rom rom.o && objcopy -I ihex -O binary rom.hex rom.bin && hexdump -v -e'1/2 "%.4X\n"' rom.bin > rom.rom && mv rom.rom ../sim/ae18_core.rom && mv rom.lst makerom.lst && rm rom.*
