#ifndef __SIM_@SCARTS_MACHINE_NAME@_H__
#define __SIM_@SCARTS_MACHINE_NAME@_H__

#define SCARTS_BOOTMEM_VMA        @SCARTS_BOOTMEM_VMA@
#define SCARTS_BOOTMEM_LMA        @SCARTS_BOOTMEM_LMA@
#define SCARTS_BOOTMEM_SIZE       @SCARTS_BOOTMEM_SIZE@
#define SCARTS_CODEMEM_VMA        @SCARTS_CODEMEM_VMA@
#define SCARTS_CODEMEM_LMA        @SCARTS_CODEMEM_LMA@
#define SCARTS_CODEMEM_SIZE       @SCARTS_CODEMEM_SIZE@
#define SCARTS_DATAMEM_VMA        @SCARTS_DATAMEM_VMA@
#define SCARTS_DATAMEM_LMA        @SCARTS_DATAMEM_LMA@
#define SCARTS_DATAMEM_SIZE       @SCARTS_DATAMEM_SIZE@
#define SCARTS_WORD_SIZE          @SCARTS_WORD_SIZE@

#endif

