# Inherit global environment
Import('env')
Import('symbols')

# The set of source files associated with this SConscript file.
src_local = ['printk.c', 'putc.c', 'string.c', 'bit.c', 'wait.c', 'mutex.c', 'idpool.c', 'memcache.c']

obj = env.Object(src_local)

Return('obj')
