# File automatically generated by "cdfg2hdl".
# Filename: cordic
# Author: Nikolaos Kavvadias (C) 2009, 2010, 2011, 2012, 2013, 2014

#!/bin/bash

make -f ../bin/cordic.mk clean
make -f ../bin/cordic.mk init
make -f ../bin/cordic.mk run

if [ "$SECONDS" -eq 1 ]
then
  units=second
else
  units=seconds
fi
echo "This script has been running for $SECONDS $units."
exit 0
