#!/bin/bash
if [${1} = '-u'] 
then
	echo STEP 1 : Compiling uart module
	echo
	cd ../../../../uart16550/sim/rtl_sim/run
	ncverilog -f ../bin/nc.scr
fi

echo STEP 2 : Compiling irda module
echo
cd ../../../../irda/sim/rtl_sim/run
ncverilog -f ../bin/nc.scr  &

