(custom-set-variables
 '(auto-revert-interval 1)
 '(global-auto-revert-mode t nil (autorevert))
 '(indent-tabs-mode nil)
 '(verilog-auto-endcomments nil)
 '(verilog-auto-indent-on-newline nil)
 '(verilog-auto-newline nil)
 '(verilog-auto-sense-defines-constant t)
 '(verilog-indent-level 4)
 '(verilog-indent-level-behavioral 4)
 '(verilog-indent-level-declaration 2)
 '(verilog-indent-level-module 0)
 '(verilog-library-directories (quote ("../../rtl/include" "../../rtl/verilog" ".")))
 '(verilog-tab-always-indent nil))
(custom-set-faces)
