./top/sdrc_top.v 
./wb2sdrc/wb2sdrc.v 
./lib/async_fifo.v  
./core/sdrc_define.v 
./core/sdrc_core.v 
./core/sdrc_bank_ctl.v 
./core/sdrc_bank_fsm.v 
./core/sdrc_bs_convert.v 
./core/sdrc_req_gen.v 
./core/sdrc_xfr_ctl.v 
