PROJ_NAME ?=group_decrypt
DEBUG ?=y

ifeq ($(DEBUG),y)
VFLAGS=-DDEBUG
else
VFLAGS=
endif

all:$(PROJ_NAME)

key_perm:

key_schedule:

block_decypher:

group_decrypt:

stream_cypher:

decrypt:

clean:
 	
