#ChipScope Core Inserter Project File Version 3.0
#Wed Jan 27 15:45:20 CET 2010
Project.device.designInputFile=/home/chrigi/bfh-work/GECKO3COM/gecko3com-ip/core/gpif_com_test_cs.ngc
Project.device.designOutputFile=/home/chrigi/bfh-work/GECKO3COM/gecko3com-ip/core/gpif_com_test_cs.ngc
Project.device.deviceFamily=6
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/chrigi/bfh-work/GECKO3COM/gecko3com-ip/core/_ngo
Project.device.useSRL16=true
Project.filter.dimension=1
Project.filter<0>=
Project.icon.boundaryScanChain=1
Project.icon.disableBUFGInsertion=false
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=i_IFCLK_BUFGP
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=o_WRX_OBUF
Project.unit<0>.dataChannel<10>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd9
Project.unit<0>.dataChannel<11>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd10
Project.unit<0>.dataChannel<12>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd11
Project.unit<0>.dataChannel<13>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd12
Project.unit<0>.dataChannel<14>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd13
Project.unit<0>.dataChannel<15>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd14
Project.unit<0>.dataChannel<16>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd15
Project.unit<0>.dataChannel<17>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd16
Project.unit<0>.dataChannel<18>=GPIF_INTERFACE s_dbus_trans_dir
Project.unit<0>.dataChannel<19>=GPIF_INTERFACE o_RX
Project.unit<0>.dataChannel<1>=i_RDYU_IBUF
Project.unit<0>.dataChannel<20>=GPIF_INTERFACE o_TX
Project.unit<0>.dataChannel<21>=GPIF_INTERFACE s_U2X_AM_FULL
Project.unit<0>.dataChannel<22>=GPIF_INTERFACE s_U2X_WR_EN
Project.unit<0>.dataChannel<23>=GPIF_INTERFACE s_X2U_EMPTY
Project.unit<0>.dataChannel<24>=GPIF_INTERFACE o_RDYX
Project.unit<0>.dataChannel<25>=s_RX_DATA<0>
Project.unit<0>.dataChannel<26>=s_RX_DATA<1>
Project.unit<0>.dataChannel<27>=s_RX_DATA<2>
Project.unit<0>.dataChannel<28>=s_RX_DATA<3>
Project.unit<0>.dataChannel<29>=s_RX_DATA<4>
Project.unit<0>.dataChannel<2>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd1
Project.unit<0>.dataChannel<30>=s_RX_DATA<5>
Project.unit<0>.dataChannel<31>=s_RX_DATA<6>
Project.unit<0>.dataChannel<32>=s_RX_DATA<7>
Project.unit<0>.dataChannel<33>=s_RX_DATA<8>
Project.unit<0>.dataChannel<34>=s_RX_DATA<9>
Project.unit<0>.dataChannel<35>=s_RX_DATA<10>
Project.unit<0>.dataChannel<36>=s_RX_DATA<11>
Project.unit<0>.dataChannel<37>=s_RX_DATA<12>
Project.unit<0>.dataChannel<38>=s_RX_DATA<13>
Project.unit<0>.dataChannel<39>=s_RX_DATA<14>
Project.unit<0>.dataChannel<3>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd2
Project.unit<0>.dataChannel<40>=s_RX_DATA<15>
Project.unit<0>.dataChannel<41>=s_EMPTY
Project.unit<0>.dataChannel<42>=i_WRU_IBUF
Project.unit<0>.dataChannel<43>=GPIF_INTERFACE s_X2U_RD_EN
Project.unit<0>.dataChannel<44>=s_RD_EN
Project.unit<0>.dataChannel<45>=GPIF_INTERFACE i_EOM
Project.unit<0>.dataChannel<46>=GPIF_INTERFACE s_X2U_FULL_IFCLK
Project.unit<0>.dataChannel<47>=
Project.unit<0>.dataChannel<4>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd3
Project.unit<0>.dataChannel<5>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd4
Project.unit<0>.dataChannel<6>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd5
Project.unit<0>.dataChannel<7>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd6
Project.unit<0>.dataChannel<8>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd7
Project.unit<0>.dataChannel<9>=GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd8
Project.unit<0>.dataDepth=512
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=47
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=i_WRU_IBUF
Project.unit<0>.triggerChannel<0><1>=o_WRX_OBUF
Project.unit<0>.triggerChannel<0><2>=o_RDYX_OBUF
Project.unit<0>.triggerChannel<0><3>=i_RDYU_IBUF
Project.unit<0>.triggerChannel<0><4>=GPIF_INTERFACE F_IN o_full
Project.unit<0>.triggerChannel<0><5>=GPIF_INTERFACE F_OUT o_empty
Project.unit<0>.triggerChannel<0><6>=GPIF_INTERFACE i_EOM
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=7
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
