#ChipScope Core Inserter Project File Version 3.0
#Sun Feb 28 00:15:45 CET 2010
Project.device.designInputFile=/home/chrigi/bfh-work/GECKO3COM/gecko3com-ip/core/GECKO3COM_simple_test_cs.ngc
Project.device.designOutputFile=/home/chrigi/bfh-work/GECKO3COM/gecko3com-ip/core/GECKO3COM_simple_test_cs.ngc
Project.device.deviceFamily=6
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/chrigi/bfh-work/GECKO3COM/gecko3com-ip/core/_ngo
Project.device.useSRL16=true
Project.filter.dimension=1
Project.filter<0>=
Project.icon.boundaryScanChain=1
Project.icon.disableBUFGInsertion=false
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=i_sysclk_BUFGP
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=GECKO3COM_simple_1 i_nReset
Project.unit<0>.dataChannel<100>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count9
Project.unit<0>.dataChannel<101>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count10
Project.unit<0>.dataChannel<102>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count11
Project.unit<0>.dataChannel<103>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count12
Project.unit<0>.dataChannel<104>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count13
Project.unit<0>.dataChannel<105>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count14
Project.unit<0>.dataChannel<106>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count15
Project.unit<0>.dataChannel<107>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count16
Project.unit<0>.dataChannel<108>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count17
Project.unit<0>.dataChannel<109>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count18
Project.unit<0>.dataChannel<10>=GECKO3COM_simple_1 s_btag_correct
Project.unit<0>.dataChannel<110>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count19
Project.unit<0>.dataChannel<111>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count20
Project.unit<0>.dataChannel<112>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count21
Project.unit<0>.dataChannel<113>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count22
Project.unit<0>.dataChannel<114>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count23
Project.unit<0>.dataChannel<115>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count24
Project.unit<0>.dataChannel<116>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count25
Project.unit<0>.dataChannel<117>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count26
Project.unit<0>.dataChannel<118>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count27
Project.unit<0>.dataChannel<119>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count28
Project.unit<0>.dataChannel<11>=GECKO3COM_simple_1 s_btag_reg_en
Project.unit<0>.dataChannel<120>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count29
Project.unit<0>.dataChannel<121>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count30
Project.unit<0>.dataChannel<122>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_btag<0>
Project.unit<0>.dataChannel<123>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_btag<1>
Project.unit<0>.dataChannel<124>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_btag<2>
Project.unit<0>.dataChannel<125>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_btag<3>
Project.unit<0>.dataChannel<126>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_btag<4>
Project.unit<0>.dataChannel<127>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_btag<5>
Project.unit<0>.dataChannel<128>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_btag<6>
Project.unit<0>.dataChannel<129>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_btag<7>
Project.unit<0>.dataChannel<12>=GECKO3COM_simple_1 s_dev_dep_msg_out
Project.unit<0>.dataChannel<130>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_msg_id<0>
Project.unit<0>.dataChannel<131>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_msg_id<1>
Project.unit<0>.dataChannel<132>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_msg_id<2>
Project.unit<0>.dataChannel<133>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_msg_id<3>
Project.unit<0>.dataChannel<134>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_msg_id<4>
Project.unit<0>.dataChannel<135>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_msg_id<5>
Project.unit<0>.dataChannel<136>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_msg_id<6>
Project.unit<0>.dataChannel<137>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_msg_id<7>
Project.unit<0>.dataChannel<138>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_nbtag<0>
Project.unit<0>.dataChannel<139>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_nbtag<1>
Project.unit<0>.dataChannel<13>=GECKO3COM_simple_1 s_eom_bit_detected
Project.unit<0>.dataChannel<140>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_nbtag<2>
Project.unit<0>.dataChannel<141>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_nbtag<3>
Project.unit<0>.dataChannel<142>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_nbtag<4>
Project.unit<0>.dataChannel<143>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_nbtag<5>
Project.unit<0>.dataChannel<144>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_nbtag<6>
Project.unit<0>.dataChannel<145>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 s_nbtag<7>
Project.unit<0>.dataChannel<14>=GECKO3COM_simple_1 s_gpif_abort
Project.unit<0>.dataChannel<15>=GECKO3COM_simple_1 s_gpif_eom
Project.unit<0>.dataChannel<16>=GECKO3COM_simple_1 s_gpif_rx_empty
Project.unit<0>.dataChannel<17>=GECKO3COM_simple_1 s_gpif_rx_rd_en
Project.unit<0>.dataChannel<18>=GECKO3COM_simple_1 s_gpif_tx_full
Project.unit<0>.dataChannel<19>=GECKO3COM_simple_1 s_gpif_tx_wr_en
Project.unit<0>.dataChannel<1>=GECKO3COM_simple_1 i_receive_fifo_rd_en
Project.unit<0>.dataChannel<20>=GECKO3COM_simple_1 s_nbtag_reg_en
Project.unit<0>.dataChannel<21>=GECKO3COM_simple_1 s_receive_counter_en
Project.unit<0>.dataChannel<22>=GECKO3COM_simple_1 s_receive_counter_load
Project.unit<0>.dataChannel<23>=GECKO3COM_simple_1 s_receive_counter_zero
Project.unit<0>.dataChannel<24>=GECKO3COM_simple_1 s_receive_end_of_message_set
Project.unit<0>.dataChannel<25>=GECKO3COM_simple_1 s_receive_fifo_full
Project.unit<0>.dataChannel<26>=GECKO3COM_simple_1 s_receive_fifo_reset
Project.unit<0>.dataChannel<27>=GECKO3COM_simple_1 s_receive_fifo_wr_en
Project.unit<0>.dataChannel<28>=GECKO3COM_simple_1 s_receive_newdata_set
Project.unit<0>.dataChannel<29>=GECKO3COM_simple_1 s_receive_transfersize_en<0>
Project.unit<0>.dataChannel<2>=GECKO3COM_simple_1 i_send_fifo_wr_en
Project.unit<0>.dataChannel<30>=GECKO3COM_simple_1 s_receive_transfersize_en<1>
Project.unit<0>.dataChannel<31>=GECKO3COM_simple_1 s_request_dev_dep_msg_in
Project.unit<0>.dataChannel<32>=GECKO3COM_simple_1 s_send_counter_en
Project.unit<0>.dataChannel<33>=GECKO3COM_simple_1 s_send_counter_load
Project.unit<0>.dataChannel<34>=GECKO3COM_simple_1 s_send_counter_zero
Project.unit<0>.dataChannel<35>=GECKO3COM_simple_1 s_send_data_request_set
Project.unit<0>.dataChannel<36>=GECKO3COM_simple_1 s_send_fifo_empty
Project.unit<0>.dataChannel<37>=GECKO3COM_simple_1 s_send_fifo_rd_en
Project.unit<0>.dataChannel<38>=GECKO3COM_simple_1 s_send_fifo_reset
Project.unit<0>.dataChannel<39>=GECKO3COM_simple_1 s_send_mux_sel<0>
Project.unit<0>.dataChannel<3>=GECKO3COM_simple_1 i_send_have_more_data
Project.unit<0>.dataChannel<40>=GECKO3COM_simple_1 s_send_mux_sel<1>
Project.unit<0>.dataChannel<41>=GECKO3COM_simple_1 s_send_mux_sel<2>
Project.unit<0>.dataChannel<42>=GECKO3COM_simple_1 GECKO3COM_simple_fsm_1 state_FSM_FFd1
Project.unit<0>.dataChannel<43>=GECKO3COM_simple_1 GECKO3COM_simple_fsm_1 state_FSM_FFd2
Project.unit<0>.dataChannel<44>=GECKO3COM_simple_1 GECKO3COM_simple_fsm_1 state_FSM_FFd3
Project.unit<0>.dataChannel<45>=GECKO3COM_simple_1 GECKO3COM_simple_fsm_1 state_FSM_FFd4
Project.unit<0>.dataChannel<46>=GECKO3COM_simple_1 GECKO3COM_simple_fsm_1 state_FSM_FFd5
Project.unit<0>.dataChannel<47>=s_transfer_size_reg_en
Project.unit<0>.dataChannel<48>=s_send_transfersize_en
Project.unit<0>.dataChannel<49>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<0>
Project.unit<0>.dataChannel<4>=GECKO3COM_simple_1 o_receive_end_of_message
Project.unit<0>.dataChannel<50>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<1>
Project.unit<0>.dataChannel<51>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<2>
Project.unit<0>.dataChannel<52>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<3>
Project.unit<0>.dataChannel<53>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<4>
Project.unit<0>.dataChannel<54>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<5>
Project.unit<0>.dataChannel<55>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<6>
Project.unit<0>.dataChannel<56>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<7>
Project.unit<0>.dataChannel<57>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<8>
Project.unit<0>.dataChannel<58>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<9>
Project.unit<0>.dataChannel<59>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<10>
Project.unit<0>.dataChannel<5>=GECKO3COM_simple_1 o_receive_fifo_empty
Project.unit<0>.dataChannel<60>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<11>
Project.unit<0>.dataChannel<61>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<12>
Project.unit<0>.dataChannel<62>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<13>
Project.unit<0>.dataChannel<63>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<14>
Project.unit<0>.dataChannel<64>=GECKO3COM_simple_1 GPIF_INTERFACE s_dbus_out<15>
Project.unit<0>.dataChannel<65>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 i_rx_data<0>
Project.unit<0>.dataChannel<66>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 i_rx_data<1>
Project.unit<0>.dataChannel<67>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 i_rx_data<2>
Project.unit<0>.dataChannel<68>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 i_rx_data<3>
Project.unit<0>.dataChannel<69>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 i_rx_data<4>
Project.unit<0>.dataChannel<6>=GECKO3COM_simple_1 o_receive_newdata
Project.unit<0>.dataChannel<70>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 i_rx_data<5>
Project.unit<0>.dataChannel<71>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 i_rx_data<6>
Project.unit<0>.dataChannel<72>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 i_rx_data<7>
Project.unit<0>.dataChannel<73>=s_send_have_more_data
Project.unit<0>.dataChannel<74>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd1
Project.unit<0>.dataChannel<75>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd2
Project.unit<0>.dataChannel<76>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd3
Project.unit<0>.dataChannel<77>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd4
Project.unit<0>.dataChannel<78>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd5
Project.unit<0>.dataChannel<79>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd6
Project.unit<0>.dataChannel<7>=GECKO3COM_simple_1 o_send_data_request
Project.unit<0>.dataChannel<80>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd7
Project.unit<0>.dataChannel<81>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd8
Project.unit<0>.dataChannel<82>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd9
Project.unit<0>.dataChannel<83>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd10
Project.unit<0>.dataChannel<84>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd11
Project.unit<0>.dataChannel<85>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd12
Project.unit<0>.dataChannel<86>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd13
Project.unit<0>.dataChannel<87>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd14
Project.unit<0>.dataChannel<88>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd15
Project.unit<0>.dataChannel<89>=GECKO3COM_simple_1 GPIF_INTERFACE FSM_GPIF pr_state_FSM_FFd16
Project.unit<0>.dataChannel<8>=GECKO3COM_simple_1 o_send_fifo_full
Project.unit<0>.dataChannel<90>=GECKO3COM_simple_1 o_receive_transfersize<0>
Project.unit<0>.dataChannel<91>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count
Project.unit<0>.dataChannel<92>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count1
Project.unit<0>.dataChannel<93>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count2
Project.unit<0>.dataChannel<94>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count3
Project.unit<0>.dataChannel<95>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count4
Project.unit<0>.dataChannel<96>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count5
Project.unit<0>.dataChannel<97>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count6
Project.unit<0>.dataChannel<98>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count7
Project.unit<0>.dataChannel<99>=GECKO3COM_simple_1 GECKO3COM_simple_datapath_1 Mcount_s_send_transfersize_count8
Project.unit<0>.dataChannel<9>=GECKO3COM_simple_1 o_send_finished
Project.unit<0>.dataDepth=512
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=146
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=GECKO3COM_simple_1 s_dev_dep_msg_out
Project.unit<0>.triggerChannel<0><10>=s_send_transfersize_en
Project.unit<0>.triggerChannel<0><11>=s_transfer_size_reg_en
Project.unit<0>.triggerChannel<0><1>=GECKO3COM_simple_1 s_gpif_tx_full
Project.unit<0>.triggerChannel<0><2>=GECKO3COM_simple_1 s_request_dev_dep_msg_in
Project.unit<0>.triggerChannel<0><3>=GECKO3COM_simple_1 s_gpif_rx_rd_en
Project.unit<0>.triggerChannel<0><4>=GECKO3COM_simple_1 s_btag_reg_en
Project.unit<0>.triggerChannel<0><5>=i_RDYU_IBUF
Project.unit<0>.triggerChannel<0><6>=s_send_data_request
Project.unit<0>.triggerChannel<0><7>=s_send_fifo_full
Project.unit<0>.triggerChannel<0><8>=GECKO3COM_simple_1 i_send_fifo_wr_en
Project.unit<0>.triggerChannel<0><9>=s_send_have_more_data
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=2
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<0><1>=0
Project.unit<0>.triggerMatchType<0><0>=0
Project.unit<0>.triggerMatchType<0><1>=0
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=12
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
