SHELL=/bin/sh
MAKE=make
CUR_DIR=$(shell pwd)
home=$(CUR_DIR)/..

all:   install


.PHONY install:
install:
	(\
	sudo apt-get  install -y emacs23;\
	sudo apt-get  install -y tcsh;\
        sudo apt-get  install -y cvs;\
        sudo apt-get  install -y subversion;\
        sudo apt-get  install -y git;\
        sudo apt-get  install -y gitk;\
        sudo apt-get  install -y git-gui;\
        sudo apt-get  install -y xutils-dev;\
        sudo apt-get  install -y tkcvs;\
	sudo apt-get  install -y perl-tk\
        sudo apt-get  install -y iverilog;\
	sudo apt-get  install -y verilator;\
        sudo apt-get  install -y covered;\
	sudo apt-get  install -y gtkterm;\
	sudo apt-get  install -y gtkwave;\
	sudo apt-get  install -y guile-1.8-dev;\
	sudo apt-get  install -y geda-gschem;\
	sudo apt-get  install -y crasm;\
	sudo apt-get  install -y libverilog-perl;\
	sudo apt-get  install -y libxml-libxml-perl;\
	sudo apt-get  install -y libxml-libusb-dev;\
	sudo apt-get  install -y libc6-dev;\
	sudo apt-get  install -y fxload;\
	sudo apt-get  install -y default-jre;\
	sudo apt-get  install -y gcc-4.4;\
	sudo apt-get  install -y g++;\
	sudo apt-get  install -y libmpfr-dev;\
	sudo apt-get  install -y libgmp3-dev;\
	sudo apt-get  install -y libmpc-dev;\
	sudo apt-get  install -y libzip-dev;\
	sudo apt-get  install -y texlive;\
	sudo apt-get  install -y flex;\
	sudo apt-get  install -y bison;\
	sudo apt-get  install -y texinfo;\
	sudo apt-get  install -y libncurses-dev;\
	sudo apt-get  install -y gperf;\
	sudo apt-get  install -y dejagnu;\
	sudo apt-get  install -y autoconf;\
	sudo apt-get  install -y build-essential;\
	sudo apt-get  install -y make;\
	sudo apt-get  install -y patch;\
	sudo apt-get  install -y python-dev;\
	sudo apt-get  install -y libexpat1-dev;\
	sudo apt-get  install -y gcc;\
	sudo apt-get  install -y libncurses5-dev;\
	sudo apt-get  install -y libftdi-dev;\
	sudo apt-get  install -y libtool;\
	sudo apt-get  install -y libelf-dev;\
	sudo apt-get  install -y elfutils;\
	sudo apt-get  install -y perl-doc;\
	sudo apt-get  install -y synaptic;\
	sudo apt-get  install -y libberkeleydb-perl;\
	sudo apt-get  install -y libscalar-util-numeric-perl;\
	sudo apt-get  install -y libparallel-forkmanager-perl;\
	)




.PHONY virtualbox:
virtualbox:
	(\
	sudo apt-get  install -y virtualbox;\
	sudo apt-get  install -y virtualbox-dkms;\
	sudo apt-get  install -y virtualbox-guest-dkms;\
	sudo apt-get  install -y virtualbox-guest-additions-iso;\
	sudo apt-get  install -y virtualbox-guest-utils;\
	sudo apt-get  install -y virtualbox-guest-x11;\
	sudo apt-get  install -y virtualbox-qt;\
	)




.PHONY nvidia:
nvidia:
	(\
	sudo apt-get  install -y nvidia-331;\
	)

.PHONY nuizy:
nuizy:
	(\
	sudo apt-get install gcc g++ python perl emacs openjdk-7-jdk gtkwave imagemagick libsdl2-dev;\
	)