
# Inherit global environment
import os, sys, glob

PROJRELROOT = '../../'

sys.path.append(PROJRELROOT)

from config.projpaths import *
from configure import *

Import('env', 'symbols')

# The set of source files associated with this SConscript file.
src_local = ['irq.c', 'platform.c', 'print-early.c', 'perfmon.c', 'cpuperf.S']

for name, val in symbols:
    if 'CONFIG_SMP' == name:
       src_local += ['smp.c']

obj = env.Object(src_local)
Return('obj')
