Import('env', 'platform')

#Platforms using pl110
plat_list = ('eb', 'pba8', 'pba9', 'pb11mpcore', 'pb926')

# The set of source files associated with this SConscript file.
src_local = []

for plat_supported in plat_list:
    if plat_supported == platform:
        src_local += Glob('*.c')

obj = env.StaticObject(src_local)
Return('obj')
