#!/bin/bash

if [[ -d ./sim/modelsim/work ]]
then
	rm -r ./sim/modelsim/work
fi

vlib ./sim/modelsim/work

vlog -work sim/modelsim/work \
     ./testbench/tb_RF.v \
     ./rtl/RF.v 

vsim -c \
     -lib ./sim/modelsim/work \
     -do ./scr/sim_tb_RF.do 

rm ./transcript


vcd2wlf ./dump/sim_tb_RF.vcd \
        ./dump/sim_tb_RF.wlf

