#!/bin/bash

if [[ -d ./sim/modelsim/work ]]
then
	rm -r ./sim/modelsim/work
fi

vlib ./sim/modelsim/work

vlog -work sim/modelsim/work \
     ./testbench/tb_WF.v \
     ./rtl/WF.v 

vsim -c \
     -lib ./sim/modelsim/work \
     -do ./scr/sim_tb_WF.do 

rm ./transcript


vcd2wlf ./dump/sim_tb_WF.vcd \
        ./dump/sim_tb_WF.wlf

