#!/bin/bash
#
# Copyright 2012, Sinclair R.F., Inc.
#
# Run all of the test benches for the peripherals.

for runname in `find -maxdepth 2 -name run | sort`; do
  cd  ${runname:0:${#runname}-4};
  echo -en "${runname:2:${#runname}-6}\r";
  ./run || { echo "Tests aborted"; exit 1; }
  cd ..
done

echo "All tests passed!";
exit 0;
