%d4_keyword = (
	  "if"     => {style =>  "keyword"},                                            
	  "then"   => {style =>  "keyword"},                                               
	  "else"   => {style =>  "keyword"},                                               
	  "elsif"  => {style =>  "keyword"},                                               
	  "for"    => {style =>  "keyword"},                                               
	  "to"     => {style =>  "keyword"},                                               
	  "integer" => {style =>  "keyword"},                                               
	  "natural" => {style =>  "keyword"},                                               
	  "boolean" => {style =>  "keyword"},                                               
	  "array"  => {style =>  "keyword"},                                               
	  "variable" => {style =>  "keyword"},                                               
	  "signal" => {style =>  "keyword"},                                               
	  "type"   => {style =>  "keyword"},                                               
	  "record" => {style =>  "keyword"},                                               
	  "function" => {style =>  "keyword"},                                               
	  "architecture" => {style =>  "keyword"},                                             
	  "wait"   => {style =>  "keyword"},                                               
	  "case"   => {style =>  "keyword"},                                               
	  "when"   => {style =>  "keyword"},                                               
	  "end"    => {style =>  "keyword"},                                               
	  "others" => {style =>  "keyword"},                                               
	  "use"    => {style =>  "keyword"},                                               
	  "library" => {style =>  "keyword"},                                               
	  "entity" => {style =>  "keyword"},                                               
	  "component" => {style =>  "keyword"},                                               
	  "port"   => {style =>  "keyword"},                                                
	  "map"    => {style =>  "keyword"},                                               
	  "in"     => {style =>  "keyword"},                                               
	  "out"    => {style =>  "keyword"},                                               
	  "inout"  => {style =>  "keyword"},                                               
	  "of"     => {style =>  "keyword"},                                               
	  "is"     => {style =>  "keyword"},                                               
	  "begin"  => {style =>  "keyword"},                                               
	  "process" => {style =>  "keyword"},
	  "std_logic" => {style =>  "variable"},
	  "std_logic_vector" => {style =>  "variable"},
	  "procedure" => {style =>  "keyword"}
); 

1;
