# GECKO3COM
#
# Copyright (C) 2008 by
#   ___    ____  _   _
#  (  _`\ (  __)( ) ( )   
#  | (_) )| (_  | |_| |   Berne University of Applied Sciences
#  |  _ <'|  _) |  _  |   School of Engineering and
#  | (_) )| |   | | | |   Information Technology
#  (____/'(_)   (_) (_)
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details. 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

TARGET = gpif_data

GECKO3MAIN :
	./edit-gpif gecko3main_gpif.c $(TARGET).c $(TARGET).h


clean :
	rm -f $(TARGET).*

.PHONY : clean GECKO3MAIN





