#!/bin/bash
CFLAGS='-g3 -O0' CXXFLAGS='-g3 -O0' ./configure \
  --prefix=$(pwd)/../../opt/bochs-2.3.7-zet \
  --enable-disasm \
  --enable-debugger \
  --disable-docbook \
  --disable-vbe \
  --disable-fpu \
  --disable-mmx \
  --enable-cpu-level=3 \
  --disable-cdrom \
  --enable-logging \
  --enable-instrumentation="instrument/zet"
