#!/usr/bin/awk -f 
# Script to convert .mem output (-v) from axasm
# to a script you can play back to the monitor via a terminal program

/@/ {
    add=substr($1,2)
    printf ("f %s \n",add);
    $1="";
    }

{
    for (i=1;i<=NF;i++)
	print $i
}

END {
    printf "\033"   
    }