#!/usr/bin/gawk -f

# Usage mergelist symfile dumpfile
# the symfile is what comes out of the axasm -H option on stderr
# the dump file is what comes out of the -H option on stdout

# process sym line
$2==":" {
    xref[$3 ":" ]=$1
    next
}

# must be dump line
   {
       if (xref[$1]!="") print xref[$1] ":"
       print
   }
