#########################
# configuration section #
#########################

# Defines the location of the EZ-USB SDK
ZTEXPREFIX=../../..

# The name of the jar archive
JARTARGET=UCEcho.jar
# Java Classes that have to be build 
CLASSTARGETS=UCEcho.class
# Extra dependencies for Java Classes
CLASSEXTRADEPS=

# ihx files (firmware ROM files) that have to be build 
IHXTARGETS=ucecho.ihx
# Extra Dependencies for ihx files
IHXEXTRADEPS=

# Extra files that should be included into th jar archive
EXTRAJARFILES=ucecho.ihx fpga/ucecho.bit

################################
# DO NOT CHANAGE THE FOLLOWING #
################################
# includes the main Makefile
include $(ZTEXPREFIX)/Makefile.mk
