# Inherit global environment
import os, sys, glob

PROJRELROOT = '../../'

sys.path.append(PROJRELROOT)

from config.projpaths import *
from configure import *

Import('env', 'symbols')


# The set of source files associated with this SConscript file.
src_local = ['head.S', 'vectors.S', 'syscall.S', 'exception-common.c', 'mapping-common.c', 'memset.S', 'memcpy.S']

for name, val in symbols:
    if 'CONFIG_SMP' == name:
	src_local += ['head-smp.S']

obj = env.Object(src_local)

Return('obj')
