#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.program(
        source='linux_init.c hi.c',
        target='hi',
		includes='../include ../include/%s' % bld.env.OS,
		cflags='-g -O0 -Wall',
        use='mcapi rt pthread',
    )

