#!/bin/bash
# Copyright 2013, Sinclair R.F., Inc.
# Run the test benches for the libraries.

NAME="char";

rm --force ssbcc;
ln -s ../../../../ssbcc;

./ssbcc -q --display-opcode -P monitor_stack uc.9x8 || { echo "FATAL ERROR testing ${NAME}" > /dev/stderr; exit 1; }
iverilog -o tb tb.v uc.v || exit 1;
if [ -n "`./tb | cmp - "tb.good" 2>&1`" ]; then
  echo "${NAME} failed" > /dev/stderr;
  exit 1;
fi
echo "Passed:  ${NAME}";

rm --force ssbcc uc.9x8-meta uc.v tb;
