#!/bin/csh
#
# test for uart
#

echo " Compiling with MODELSIM "

if(! -e work) then
   vlib work
endif

vlog -work work -f filelist.f | tee ../log/compile.log


vsim -do modelsim.do -c tb | tee  ../log/run.log
