; $Id: testerr_0130_Terror_inst.mac 501 2013-03-30 13:53:39Z mueller $
;
; test T error code (Truncation)
; truncation in instruction fields
;
        .asect
        .blkw   400

        spl     7
        spl     17              ;;!! T

        mark    77
        mark    100             ;;!! T

        trap    377
        trap    400             ;;!! T

        emt     377
        emt     400             ;;!! T

        .end
