; $Id: testerr_0100_Berror.mac 501 2013-03-30 13:53:39Z mueller $
;
; test B error code (bounding error)
;
        .asect
        .blkw   400

; word align code

t1:     inc     r0
1$:     .byte   0
2$:
        inc     r1              ;;!! B

; word align .word

t2:     .word   0
1$:     .byte   1
2$:
        .word   2               ;;!! B

; word align .blkw

t3:     .blkw   2
1$:     .blkb   3
2$:
        .blkw   2               ;;!! B

        .end
