; $Id: testerr_0020_muldef_label.mac 501 2013-03-30 13:53:39Z mueller $
;
; test multiple defined label response
;
        .asect

; for normal labels

zero:   .word   zero            ;;!! DM
one:    .word   one
zero:   .word   0               ;;!! M
        .word   zero            ;;!! D

; for local labels (in scope)

blk1:   .word   0
1$:     .word   1               ;;!! M
2$:     .word   2
1$:     .word   3               ;;!! M
        .word   1$              ;;!! D
        .word   2$

        .end
