; $Id: testerr_0010_undef_label.mac 501 2013-03-30 13:53:39Z mueller $
;
; test undefined label response
;
        .asect

; for normal labels

zero:   .word   zero
        .word   one             ;;!! U
        .word   two             ;;!! U

; for local labels (in scope)

blk1:   .word   0
1$:     .word   blk1
        .word   1$
        .word   2$              ;;!! U

; for local labels (out-of-scope)

blk2:   .word   0
2$:     .word   1$              ;;!! U
        .word   2$

        .end
