#
# Makefile to synthesize the project (this is only a dummy)
#

all:
		@echo "Please use Xilinx ISE 14.5 to synthesize the project!"

clean:
		mv lfsr128/lfsr128.xise .
		rm -rf lfsr128/*
		mv lfsr128.xise lfsr128
		rm -f *~
