#!/usr/bin/env python

def configure(conf):
	conf.env.LIB_pthread = ['pthread']
	conf.env.LIB_rt = ['rt']

def build(bld):
	bld.recurse('support_suite')

	includes = [
		'.',
		'../include',
		'../include/%s' % bld.env.OS,
		'../libmcapi/include',
		'support_suite/%s' % bld.env.OS
	]

	func_frontend_sources = [
		'func/frontend.c',
		'func/fts_mcapi_cancel.c',
		'func/fts_mcapi_connect_pktchan_i.c',
		'func/fts_mcapi_connect_sclchan_i.c',
		'func/fts_mcapi_create_endpoint.c',
		'func/fts_mcapi_delete_endpoint.c',
		'func/fts_mcapi_get_endpoint.c',
		'func/fts_mcapi_get_endpoint_attribute.c',
		'func/fts_mcapi_get_endpoint_i.c',
		'func/fts_mcapi_msg_available.c',
		'func/fts_mcapi_msg_recv.c',
		'func/fts_mcapi_msg_recv_i.c',
		'func/fts_mcapi_msg_send.c',
		'func/fts_mcapi_msg_send_i.c',
		'func/fts_mcapi_open_pktchan_recv_i.c',
		'func/fts_mcapi_open_pktchan_send_i.c',
		'func/fts_mcapi_open_sclchan_recv_i.c',
		'func/fts_mcapi_open_sclchan_send_i.c',
		'func/fts_mcapi_pktchan_available.c',
		'func/fts_mcapi_pktchan_free.c',
		'func/fts_mcapi_pktchan_recv.c',
		'func/fts_mcapi_pktchan_recv_close_i.c',
		'func/fts_mcapi_pktchan_recv_i.c',
		'func/fts_mcapi_pktchan_send.c',
		'func/fts_mcapi_pktchan_send_close_i.c',
		'func/fts_mcapi_pktchan_send_i.c',
		'func/fts_mcapi_sclchan_available.c',
		'func/fts_mcapi_sclchan_recv_close_i.c',
		'func/fts_mcapi_sclchan_recv_x.c',
		'func/fts_mcapi_sclchan_send_close_i.c',
		'func/fts_mcapi_sclchan_send_x.c',
		'func/fts_mcapi_set_endpoint_attribute.c',
		'func/fts_mcapi_test.c',
		'func/fts_mcapi_wait.c',
		'func/fts_mcapi_wait_any.c',
	]

	func_backend_sources = [
		'func/backend.c',
	]

	bld.env.prepend_value('CFLAGS', ['-O2', '-Wall'])

	bld.stlib(
		target='mgmt',
		source='mgmt_svc.c',
		includes=' '.join(includes),
	)

	bld.program(
		target='func_frontend',
		source=' '.join(func_frontend_sources),
		includes=' '.join(includes),
		use='mgmt test_support mcapi pthread rt'
	)

	bld.program(
		target='func_backend',
		source=' '.join(func_backend_sources),
		includes=' '.join(includes),
		use='mgmt test_support mcapi pthread rt'
	)

	bld.program(
		target='api_suite',
		source='3/mcapi_tests.c',
		includes=' '.join(includes),
		use='mcapi test_support pthread rt'
	)

def options(opt):
	pass
