#!/bin/bash
DIR=${0%/*}
if [ -r $DIR/DeviceServer.jar ]; then
    java -cp $DIR/DeviceServer.jar DeviceServer $@
else 
    export CLASSPATH=$CLASSPATH:/usr/local/share/java:/usr/share/java
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib
    java DeviceServer $@
fi    
