import os, sys, glob

PROJRELROOT = '../../'

sys.path.append(PROJRELROOT)

from config.projpaths import *
from configure import *

Import("env", "symbols", "platform", "bdir")

src_local = []
objs = []

for name, val in symbols:
    if "CONFIG_DRIVER_UART_PL011" == name:
	    objs += SConscript("uart/pl011/SConscript", exports = {'env' : env}, duplicate=0, build_dir=bdir + 'pl011')
    if "CONFIG_DRIVER_TIMER_SP804" == name:
	    objs += SConscript("timer/sp804/SConscript", exports = {'env' : env}, duplicate=0, build_dir=bdir + 'timer')
    if "CONFIG_DRIVER_IRQ_PL190" == name:
	    objs += SConscript("irq/pl190/SConscript", exports = {'env' : env}, duplicate=0, build_dir=bdir + 'vic')
    if "CONFIG_DRIVER_IRQ_GIC" == name:
	    objs += SConscript("irq/gic/SConscript", exports = {'env' : env}, duplicate=0, build_dir=bdir + 'gic')
    if "CONFIG_DRIVER_INTC_OMAP" == name:
	    objs += SConscript("irq/omap3/SConscript", exports = {'env' : env}, duplicate=0, build_dir=bdir + '/omap/intc')
    if "CONFIG_DRIVER_UART_OMAP" == name:
       	objs += SConscript("uart/omap/SConscript", exports = {'env' : env}, duplicate=0, build_dir=bdir + '/omap/uart')
    if "CONFIG_DRIVER_TIMER_OMAP" == name:
    	objs += SConscript("timer/omap/SConscript", exports = {'env' : env}, duplicate=0, build_dir=bdir + '/omap/timer')


Return('objs')
