# $Id: Makefile,v 1.1.1.1 2005-01-04 02:06:00 arif_endro Exp $
#

all       :
	vasy -V -o bench.vhdl
verilog       :
	vasy -V -v -o bench.vhdl
clean_vhd :
	rm -v -f *.vhd
clean_v   :
	rm -v -f *.v
clean_vbe :
	rm -v -f *.vbe
clean    :
	echo "use make clean_vbe, clean_vhd, clean_v to clean up"
