#! /bin/sh
asid=1664
imaje=imita.1664.imaje
radi=../../..
cd ../
cd ../lista;make instala
cd ../linux;make instala
cd ../cpu_1664;make instala
cd ASID;make instala
$asid $1 -v -I $radi/arci/1664/fonte/lista -I $radi/arci/1664 -I $radi/arci/1664/inclui -f $radi/arci/1664/dev/0.imita.0.1664 -b $imaje
$asid $1 -I $radi/arci/1664/inclui -I $radi/arci/1664/dev -f 0.base.opera.1664 -B $imaje -e +parametre_1664
rm $imaje