#!/bin/bash

# Take from the trace.vcd file (passed as argument)
# only the lines of outgoing and incoming packets
# (read README.txt for details).

if ( test $# != 1 ) then
  echo "Tracan - Trace Analyzer";
  echo "(C) 2006 by Simply RISC";
  echo "Usage:";
  echo "      tracan <VCDFILE>";
  echo "";
  exit 1;
fi

if (! test -e tracan.bin) then gcc -o tracan.bin tracan.c; fi

egrep ' "$| \$$' $1 | egrep -v x | ./tracan.bin

