#########################
# configuration section #
#########################

ZTEXPREFIX=../../..

JARTARGET=FlashBench.jar
CLASSTARGETS=FlashBench.class
CLASSEXTRADEPS=
#CLASSEXTRADEPS:=$(wildcard $(ZTEXPREFIX)/java/ztex/*.java)

IHXTARGETS=flashbench.ihx
IHXEXTRADEPS=
#IHXEXTRADEPS:=$(wildcard $(ZTEXPREFIX)/include/*.h)
EXTRAJARFILES=flashbench.ihx

################################
# DO NOT CHANAGE THE FOLLOWING #
################################

include $(ZTEXPREFIX)/Makefile.mk
