VERSION 6
BEGIN SCHEMATIC
    BEGIN ATTR DeviceFamilyName "spartan2e"
        DELETE all:0
        EDITNAME all:0
        EDITTRAIT all:0
    END ATTR
    BEGIN NETLIST
    END NETLIST
    BEGIN SHEET 1 3520 2720
    END SHEET
END SCHEMATIC
