

# Inherit global environment
Import('env')

# The set of source files associated with this SConscript file.
src_local = ['mapping.c', 'exception.c', 'mmu_ops.S', 'cache.c', 'mutex.c', 'irq.c', 'init.c', 'atomic.S']

obj = env.Object(src_local)
Return('obj')
