# Makefile for AVR code.
AS= as
CC= gcc
LD= ld

CFLAGS= -g -Wall -DWITH_DEBUG
LDFLAGS=
LIBS= -lpthread
TARGET=testbus

# Avr program modules
SRCS= buf.c dispatch.c req.c skeletondev.c testbus.c encdec.c

OBJS= $(SRCS:.c=.o)

all: $(TARGET)


$(TARGET): 
	$(CC) $(CFLAGS) $(SRCS) -o $@ $(LIBS)

clean:
	rm -f $(OBJS) $(TARGET)
