#!/bin/sh

# $Id: acrobat_view,v 1.1.1.1 2005-12-06 02:47:48 arif_endro Exp $
# Generate pdf file then view using acrobat

SOURCE="mini_aes"
INPUT="${SOURCE}.tex"
ACROREAD="`which acroread`"
# ACROREAD="/opt/acroread-5.0.8/bin/acroread"

if [ -f ${INPUT} ]
then
	# Clean up and regenerate dvi file
	make real_clean dvi
fi

INTERMEDIATE="${SOURCE}.dvi"
if [ -f ${INTERMEDIATE} ]
then
	# Generate ps pdf and clean auxiliary file
	make -B dvi ps pdf clean
fi

# View using acrobat reader
FILE="${SOURCE}.pdf"
if [ -f ${FILE} ]
then
	${ACROREAD} ${FILE}
fi
