#!/bin/bash
export SYMPHONYEDA="/usr/local/Simili31"
. /usr/local/Simili31/bin/init.sh
../scripts/bscan_compile_simili compile.simili.files -log compile.simili.results -lib main_lib
../scripts/bscan_compile_simili compile_alu.simili.files -log compile_alu.simili.results -lib main_lib
../scripts/bscan_sim_simili alu_bscan_tester
