all:
	iverilog -y. -y./../../rtl/ao486/ -y./../../rtl/ao486/memory/ -y./../../rtl/ao486/pipeline -y./../../rtl/ao486/autogen -y./../../rtl/ao486/altera -y./../altera/ -I./../../rtl/ao486/ -o tb_ao486_run.vvp tb_ao486_run.v
	