# -*- mode: python; coding: utf-8; -*-
#
#  Codezero -- a microkernel for embedded systems.
#
#  Copyright © 2009  B Labs Ltd
#

Import('env')

e = env.Clone()
e.Append(CPPPATH = ['include'])
e.Append(CCFLAGS = '-nostdinc')

objects = e.StaticObject(Glob('src/*.c'))
library = e.StaticLibrary('elf', objects)

Return('library')
