vlib modelsim
vlib modelsim/grlib 
vlib modelsim/unisim 
vlib modelsim/dw02 
vlib modelsim/synplify 
vlib modelsim/techmap 
vlib modelsim/spw 
vlib modelsim/eth 
vlib modelsim/opencores 
vlib modelsim/gaisler 
vlib modelsim/esa 
vlib modelsim/micron 
vlib modelsim/work 
