-- This file is automatically generated by a matlab script 
--
-- Do not modify directly!
--

library ieee;
use ieee.std_logic_1164.all;
use IEEE.STD_LOGIC_arith.all;
use IEEE.STD_LOGIC_signed.all;

package sine_lut_pkg is

constant PHASE_WIDTH : integer := 8;
constant AMPL_WIDTH : integer := 14;

type lut_type is array(0 to 2**(PHASE_WIDTH-2)-1) of std_logic_vector(AMPL_WIDTH-1 downto 0);

	constant sine_lut : lut_type := (
    conv_std_logic_vector(0,AMPL_WIDTH),
    conv_std_logic_vector(201,AMPL_WIDTH),
    conv_std_logic_vector(402,AMPL_WIDTH),
    conv_std_logic_vector(603,AMPL_WIDTH),
    conv_std_logic_vector(803,AMPL_WIDTH),
    conv_std_logic_vector(1003,AMPL_WIDTH),
    conv_std_logic_vector(1202,AMPL_WIDTH),
    conv_std_logic_vector(1400,AMPL_WIDTH),
    conv_std_logic_vector(1598,AMPL_WIDTH),
    conv_std_logic_vector(1795,AMPL_WIDTH),
    conv_std_logic_vector(1990,AMPL_WIDTH),
    conv_std_logic_vector(2185,AMPL_WIDTH),
    conv_std_logic_vector(2378,AMPL_WIDTH),
    conv_std_logic_vector(2569,AMPL_WIDTH),
    conv_std_logic_vector(2759,AMPL_WIDTH),
    conv_std_logic_vector(2948,AMPL_WIDTH),
    conv_std_logic_vector(3135,AMPL_WIDTH),
    conv_std_logic_vector(3319,AMPL_WIDTH),
    conv_std_logic_vector(3502,AMPL_WIDTH),
    conv_std_logic_vector(3683,AMPL_WIDTH),
    conv_std_logic_vector(3861,AMPL_WIDTH),
    conv_std_logic_vector(4037,AMPL_WIDTH),
    conv_std_logic_vector(4211,AMPL_WIDTH),
    conv_std_logic_vector(4382,AMPL_WIDTH),
    conv_std_logic_vector(4551,AMPL_WIDTH),
    conv_std_logic_vector(4716,AMPL_WIDTH),
    conv_std_logic_vector(4879,AMPL_WIDTH),
    conv_std_logic_vector(5039,AMPL_WIDTH),
    conv_std_logic_vector(5196,AMPL_WIDTH),
    conv_std_logic_vector(5350,AMPL_WIDTH),
    conv_std_logic_vector(5501,AMPL_WIDTH),
    conv_std_logic_vector(5648,AMPL_WIDTH),
    conv_std_logic_vector(5792,AMPL_WIDTH),
    conv_std_logic_vector(5932,AMPL_WIDTH),
    conv_std_logic_vector(6069,AMPL_WIDTH),
    conv_std_logic_vector(6202,AMPL_WIDTH),
    conv_std_logic_vector(6332,AMPL_WIDTH),
    conv_std_logic_vector(6457,AMPL_WIDTH),
    conv_std_logic_vector(6579,AMPL_WIDTH),
    conv_std_logic_vector(6697,AMPL_WIDTH),
    conv_std_logic_vector(6811,AMPL_WIDTH),
    conv_std_logic_vector(6920,AMPL_WIDTH),
    conv_std_logic_vector(7026,AMPL_WIDTH),
    conv_std_logic_vector(7127,AMPL_WIDTH),
    conv_std_logic_vector(7224,AMPL_WIDTH),
    conv_std_logic_vector(7316,AMPL_WIDTH),
    conv_std_logic_vector(7405,AMPL_WIDTH),
    conv_std_logic_vector(7488,AMPL_WIDTH),
    conv_std_logic_vector(7567,AMPL_WIDTH),
    conv_std_logic_vector(7642,AMPL_WIDTH),
    conv_std_logic_vector(7712,AMPL_WIDTH),
    conv_std_logic_vector(7778,AMPL_WIDTH),
    conv_std_logic_vector(7838,AMPL_WIDTH),
    conv_std_logic_vector(7894,AMPL_WIDTH),
    conv_std_logic_vector(7946,AMPL_WIDTH),
    conv_std_logic_vector(7992,AMPL_WIDTH),
    conv_std_logic_vector(8034,AMPL_WIDTH),
    conv_std_logic_vector(8070,AMPL_WIDTH),
    conv_std_logic_vector(8102,AMPL_WIDTH),
    conv_std_logic_vector(8129,AMPL_WIDTH),
    conv_std_logic_vector(8152,AMPL_WIDTH),
    conv_std_logic_vector(8169,AMPL_WIDTH),
    conv_std_logic_vector(8181,AMPL_WIDTH),
    conv_std_logic_vector(8181,AMPL_WIDTH)
	);

end sine_lut_pkg;

package body sine_lut_pkg is
end sine_lut_pkg;