

# Inherit global environment
Import('env')

# The set of source files associated with this SConscript file.
src_local = ['print-early.c', 'platform.c', 'perfmon.c', 'irq.c', 'cm.c']

obj = env.Object(src_local)

Return('obj')
