\input texinfo       @c                    -*- Texinfo -*-
@setfilename cgen.info

@include version.texi

@ifinfo
@format
START-INFO-DIR-ENTRY
* Cgen: (cgen).                 The Cpu tools GENerator.
END-INFO-DIR-ENTRY
@end format
@end ifinfo

@copying
Copyright @copyright{} 2000, 2007, 2009 Red Hat, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions.
@end copying

@synindex ky cp
@c
@c This file documents the Cpu tools GENerator, CGEN.
@c
@c Copyright (C) 2000, 2009 Red Hat, Inc.
@c

@setchapternewpage odd
@settitle CGEN
@titlepage
@finalout
@title The Cpu tools GENerator, CGEN.
@subtitle Version @value{VERSION}
@sp 1
@subtitle @value{UPDATED}
@author Douglas J. Evans
@page

@tex
{\parskip=0pt \hfill Red Hat\par \hfill
\TeX{}info \texinfoversion\par }
@end tex

@vskip 0pt plus 1filll
Copyright @copyright{} 2000, 2009 Red Hat, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions.
@end titlepage

@node Top
@top Introduction

@cindex version
This manual documents the CGEN program,
version @value{VERSION}.

@menu
* Introduction::                Introduction
* Running CGEN::		How to run CGEN
* RTL::                         The Register Transfer Language CGEN uses
* Preprocessor macros::         Macros to simplify description file writing
* Porting::                     Porting
* Opcodes::                     Assembler/disassembler support
* Simulation::                  Simulation support
* Writing an application::      Writing your own CGEN application
* Glossary::                    Glossary
* Miscellaneous notes::         Notes needing a better home
* Credits::			Credits
* Index::                       Index
@end menu

@include intro.texi
@include running.texi
@include rtl.texi
@include pmacros.texi
@include porting.texi
@include opcodes.texi
@include sim.texi
@include app.texi
@include glossary.texi
@include notes.texi
@include credits.texi

@node Index
@unnumbered Index

@printindex cp

@contents
@bye
