@c Copyright (C) 2000, 2009 Red Hat, Inc.
@c This file is part of the CGEN manual.
@c For copying conditions, see the file cgen.texi.

@node Glossary
@chapter Glossary

@table @asis

@item arch
This is the overall architecture.  It is the same as BFD's use of
@emph{arch}.

@item isa
Acronym for Instruction Set Architecture.

@item mach
This is a variant of the architecture, short for machine.  It is
essentially the same as BFD's use of @emph{mach}.

@item cpu family
A group of related mach's.  Simulator support is organized along ``cpu
family'' lines to keep related machs together under one roof to
simplify things.  The organization is semi-arbitrary and is up to the
programmer.

@item model
An implementation of a mach.  It is essentially akin to the argument
to @code{-mtune=} in SPARC GCC (and other GCC ports).

@item ifield
An instruction field.

@item iformat
An instruction format, as specified by the instruction's fields.

@item sformat
An instruction semantic format.
This is different from @code{iformat}.
For example, if an operand is referred to in one mode by
one instruction and in a different mode by another instruction, then these
two insns would have different sformats even if they have the same iformat.

@item insn
An instruction.

@end table
