#!/bin/bash
#
# Copyright 2013, Sinclair R.F., Inc.

NAME=AXI4_Lite_Slave_DualPortRAM

for RAM in ram8 ram32; do
  sed -e "s/@RAM@/${RAM}/" tb_AXI4_Lite_Slave_DualPortRAM.9x8-template > tb_AXI4_Lite_Slave_DualPortRAM.9x8;
  ../../../../../ssbcc -q --display-opcode -P monitor_stack tb_${NAME}.9x8 || { echo "${NAME} compile failed" > /dev/stderr; exit 1; }
  iverilog -o tb tb.v tb_${NAME}.v || { echo "${NAME} build failed" > /dev/stderr; exit 1; }
  ./tb > tb.out;
  if ! cmp -s tb.out tb.good; then
    echo "${NAME} failed" > /dev/stderr;
    exit 1;
  fi
done

echo "Passed:  ${NAME}";
exit 0;
