# Inherit global environment
Import('env')
Import('symbols')

# The set of source files associated with this SConscript file.
src_local = ['kip.c', 'syscall.c', 'thread.c', 'ipc.c', 'map.c', 'mutex.c', 'cap.c', 'exregs.c', 'irq.c', 'cache.c']

obj = env.Object(src_local)

Return('obj')
