#!/bin/sh
rm -f tmp_ml40x____datafile.ace
cp -f $XILINX/xcfp/data/xcf32p_vo48.bsd .
cp -f $XILINX/xc9500xl/data/xc95144xl_tq100.bsd .
cp -f $1 tmp_ml40x____datafile.bit
$XILINX/bin/lin64/impact -batch $3/ml40x.scr
$XILINX/bin/lin64/impact -batch $3/ml40x_svf2ace.scr
rm -f tmp_ml40x____datafile.bit
rm -f tmp_ml40x____datafile.svf
rm -f $2
mv -f tmp_ml40x____datafile.ace $2
