#ifndef CONFIG_DDR2SP
#define CONFIG_DDR2SP 0
#endif

#ifndef CONFIG_DDR2SP_INIT
#define CONFIG_DDR2SP_INIT 0
#endif

#ifndef CONFIG_DDR2SP_FREQ
#define CONFIG_DDR2SP_FREQ 100
#endif

#ifndef CONFIG_DDR2SP_TRFC
#define CONFIG_DDR2SP_TRFC 130
#endif

#ifndef CONFIG_DDR2SP_DATAWIDTH
#define CONFIG_DDR2SP_DATAWIDTH 64
#endif

#ifndef CONFIG_DDR2SP_COL
#define CONFIG_DDR2SP_COL 9
#endif

#ifndef CONFIG_DDR2SP_MBYTE
#define CONFIG_DDR2SP_MBYTE 8
#endif

#ifndef CONFIG_DDR2SP_RSKEW
#define CONFIG_DDR2SP_RSKEW 0
#endif

#ifndef CONFIG_DDR2SP_DELAY0
#define CONFIG_DDR2SP_DELAY0 0
#endif

#ifndef CONFIG_DDR2SP_DELAY1
#define CONFIG_DDR2SP_DELAY1 0
#endif

#ifndef CONFIG_DDR2SP_DELAY2
#define CONFIG_DDR2SP_DELAY2 0
#endif

#ifndef CONFIG_DDR2SP_DELAY3
#define CONFIG_DDR2SP_DELAY3 0
#endif

#ifndef CONFIG_DDR2SP_DELAY4
#define CONFIG_DDR2SP_DELAY4 0
#endif

#ifndef CONFIG_DDR2SP_DELAY5
#define CONFIG_DDR2SP_DELAY5 0
#endif

#ifndef CONFIG_DDR2SP_DELAY6
#define CONFIG_DDR2SP_DELAY6 0
#endif

#ifndef CONFIG_DDR2SP_DELAY7
#define CONFIG_DDR2SP_DELAY7 0
#endif
