ACTEL:
	vppp +define+RAM_WB_DAT_WIDTH+32 +define+RAM_WB_ADR_WIDTH+11 +define+RAM_WB_MEM_SIZE+2048 --simple ram_wb_sc_dw.v > ram_wb_sc_dw_32x2048.v
	vppp +define+RAM_WB_DAT_WIDTH+32 +define+RAM_WB_ADR_WIDTH+10 +define+RAM_WB_MEM_SIZE+1024 --simple ram_wb_sc_dw.v > ram_wb_sc_dw_32x1024.v

all: ACTEL
