../../../src/pcie_src/pcie_core64_m1/source/pcie_clocking.v
../../../src/pcie_src/pcie_core64_m1/source/prod_fixes.v
../../../src/pcie_src/pcie_core64_m1/source/bram_common.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_mim_wrapper.v
../../../src/pcie_src/pcie_core64_m1/source/tx_sync_gtp.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_gt_wrapper.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_gt_wrapper_top.v
../../../src/pcie_src/pcie_core64_m1/source/extend_clk.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_ll_arb.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_ll_tx.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_ll_tx_arb.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_plus_ll_tx.v
../../../src/pcie_src/pcie_core64_m1/source/sync_fifo.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_ll_oqbqfifo.v
../../../src/pcie_src/pcie_core64_m1/source/cmm_decoder.v
../../../src/pcie_src/pcie_core64_m1/source/tlm_rx_data_snk_mal.v
../../../src/pcie_src/pcie_core64_m1/source/tlm_rx_data_snk_pwr_mgmt.v
../../../src/pcie_src/pcie_core64_m1/source/tlm_rx_data_snk_bar.v
../../../src/pcie_src/pcie_core64_m1/source/tlm_rx_data_snk.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_plus_ll_rx.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_ll_credit.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_ll.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_cf_arb.v
../../../src/pcie_src/pcie_core64_m1/source/cmm_errman_cor.v
../../../src/pcie_src/pcie_core64_m1/source/cmm_errman_cnt_en.v
../../../src/pcie_src/pcie_core64_m1/source/cmm_errman_ftl.v
../../../src/pcie_src/pcie_core64_m1/source/cmm_errman_cpl.v
../../../src/pcie_src/pcie_core64_m1/source/cmm_errman_ram4x26.v
../../../src/pcie_src/pcie_core64_m1/source/cmm_errman_ram8x26.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_cf_err.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_cf_mgmt.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_cf_pwr.v
../../../src/pcie_src/pcie_core64_m1/source/cmm_intr.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_soft_int.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_cf.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_blk_if.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_reset_logic.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_top.v
../../../src/pcie_src/pcie_core64_m1/source/pcie_ep.v
../../../src/pcie_src/pcie_core64_m1/source/ctrl_pcie_x8.v

../../../src/pcie_src/pcie_sim/dsport/glbl.v
