rootURL = "http://www.xilinx.com/";
prodURL = "xlnx/xil_prodcat_product.jsp?title=";
cpldURL = "CPLD+Products";
acr2URL = "coolrunner2_page";
xbrURL = "coolrunner2_page";
xpla3URL = "xpla3_page";
xc9500URL = "xc9500_page";
xc9500xlURL = "xc9500xl_page";
xa9500xlURL = "xc9500xl_page";
xc9500xvURL = "xc9500xv_page";
marketURL= "esp";
supportURL = "http://www.support.xilinx.com/";
educationURL = "support/education-home.htm";
buyURL = "http://toolbox.xilinx.com/cgi-bin/xilinx.storefront";
contactURL = "company/contact.htm";
searchURL = "company/search.htm";

docURL = rootURL + "xlnx/xweb/xil_publications_display.jsp?" +
         "iLanguageID=1" +
         "&category=/Data+Sheets/CPLD+Device+Families/";
doc95URL = docURL + "XC9500";
doc95xlURL = docURL + "XC9500XL";
docA95xlURL = docURL + "XC9500XL";
doc95xvURL = docURL + "XC9500XV";
docXpla3URL = docURL + "CoolRunner+XPLA3";
docAcr2URL = docURL + "CoolRunner-II";
docXbrURL = docURL + "CoolRunner-II";
docCr2sURL = docURL + "CoolRunner-IIS";

var messages = new Array();
messages["fastinreg"] = "Direct Input Register";
messages["inreg"] = "Direct Input Register";
messages["fbnand"] = "Foldback NAND";
messages["fcnode"] = "FC node";
messages["LATCH"] = "Transparent latch";
messages["DFF"] = "D-flip-flop";
messages["DEFF"] = "D-flip-flop with clock enable";
messages["TFF"] = "T-flip-flop";
messages["TDFF"] = "Dual-edge-triggered T-flip-flop";
messages["DDFF"] = "Dual-edge-triggered flip-flop";
messages["DDEFF"] = "Dual-edge-triggered flip-flop with clock enable";
