#ifndef CONFIG_GRUSBHC_ENABLE
#define CONFIG_GRUSBHC_ENABLE 0
#endif

#ifndef CONFIG_GRUSBHC_NPORTS
#define CONFIG_GRUSBHC_NPORTS 1
#endif

#ifndef CONFIG_GRUSBHC_EHC
#define CONFIG_GRUSBHC_EHC 0
#endif

#ifndef CONFIG_GRUSBHC_UHC
#define CONFIG_GRUSBHC_UHC 0
#endif

#ifndef CONFIG_GRUSBHC_NCC
#define CONFIG_GRUSBHC_NCC 1
#endif

#ifndef CONFIG_GRUSBHC_NPCC
#define CONFIG_GRUSBHC_NPCC 1
#endif

#ifndef CONFIG_GRUSBHC_PRR
#define CONFIG_GRUSBHC_PRR 0
#endif

#ifndef CONFIG_GRUSBHC_ENDIAN
#define CONFIG_GRUSBHC_ENDIAN 1
#endif

#ifndef CONFIG_GRUSBHC_BLO
#define CONFIG_GRUSBHC_BLO 3
#endif

#ifndef CONFIG_GRUSBHC_BEREGS
#define CONFIG_GRUSBHC_BEREGS 0
#endif

#ifndef CONFIG_GRUSBHC_BEDESC
#define CONFIG_GRUSBHC_BEDESC 0
#endif

#ifndef CONFIG_GRUSBHC_BWRD
#define CONFIG_GRUSBHC_BWRD 16
#endif

#if defined CONFIG_GRUSBHC_UTMI16
#define CONFIG_GRUSBHC_UTMTYPE 0
#if defined CONFIG_GRUSBHC_ENABLEH
#if defined CONFIG_GRUSBHC_FAULT2H
#define CONFIG_GRUSBHC_VBUSCONF 3
#else
#define CONFIG_GRUSBHC_VBUSCONF 1
#endif
#else
#if defined CONFIG_GRUSBHC_FAULT2H
#define CONFIG_GRUSBHC_VBUSCONF 2
#else
#define CONFIG_GRUSBHC_VBUSCONF 0
#endif
#endif
#elif defined CONFIG_GRUSBHC_UTMI8
#define CONFIG_GRUSBHC_UTMTYPE 1
#if defined CONFIG_GRUSBHC_ENABLEH
#if defined CONFIG_GRUSBHC_FAULT2H
#define CONFIG_GRUSBHC_VBUSCONF 3
#else
#define CONFIG_GRUSBHC_VBUSCONF 1
#endif
#else
#if defined CONFIG_GRUSBHC_FAULT2H
#define CONFIG_GRUSBHC_VBUSCONF 2
#else
#define CONFIG_GRUSBHC_VBUSCONF 0
#endif
#endif
#else
#define CONFIG_GRUSBHC_UTMTYPE 2
#if defined CONFIG_GRUSBHC_VBUSINT
#define CONFIG_GRUSBHC_VBUSCONF 0
#else
#if defined CONFIG_GRUSBHC_FAULTL
#define CONFIG_GRUSBHC_VBUSCONF 3
#elif defined CONFIG_GRUSBHC_FAULTH
#define CONFIG_GRUSBHC_VBUSCONF 2
#else
#define CONFIG_GRUSBHC_VBUSCONF 1
#endif
#endif
#endif


#ifndef CONFIG_GRUSBHC_VBUSCONF
#define CONFIG_GRUSBHC_VBUSCONF 3
#endif

#ifndef CONFIG_GRUSBHC_PR1
#define CONFIG_GRUSBHC_PR1 1
#endif
#ifndef CONFIG_GRUSBHC_PR2
#define CONFIG_GRUSBHC_PR2 0
#endif
#ifndef CONFIG_GRUSBHC_PR3
#define CONFIG_GRUSBHC_PR3 0
#endif
#ifndef CONFIG_GRUSBHC_PR4
#define CONFIG_GRUSBHC_PR4 0
#endif
#ifndef CONFIG_GRUSBHC_PR5
#define CONFIG_GRUSBHC_PR5 0
#endif
#ifndef CONFIG_GRUSBHC_PR6
#define CONFIG_GRUSBHC_PR6 0
#endif
#ifndef CONFIG_GRUSBHC_PR7
#define CONFIG_GRUSBHC_PR7 0
#endif
#ifndef CONFIG_GRUSBHC_PR8
#define CONFIG_GRUSBHC_PR8 0
#endif
#ifndef CONFIG_GRUSBHC_PR9
#define CONFIG_GRUSBHC_PR9 0
#endif
#ifndef CONFIG_GRUSBHC_PR10
#define CONFIG_GRUSBHC_PR10 0
#endif
#ifndef CONFIG_GRUSBHC_PR11
#define CONFIG_GRUSBHC_PR11 0
#endif
#ifndef CONFIG_GRUSBHC_PR12
#define CONFIG_GRUSBHC_PR12 0
#endif
#ifndef CONFIG_GRUSBHC_PR13
#define CONFIG_GRUSBHC_PR13 0
#endif
#ifndef CONFIG_GRUSBHC_PR14
#define CONFIG_GRUSBHC_PR14 0
#endif
#ifndef CONFIG_GRUSBHC_PR15
#define CONFIG_GRUSBHC_PR15 0
#endif

#define CONFIG_GRUSBHC_PORTROUTE1 CONFIG_GRUSBHC_PR8*2**26 + CONFIG_GRUSBHC_PR7*2**22 +\
                                  CONFIG_GRUSBHC_PR6*2**18 + CONFIG_GRUSBHC_PR5*2**14 +\
                                  CONFIG_GRUSBHC_PR4*2**10 + CONFIG_GRUSBHC_PR3*2**6 +\
                                  CONFIG_GRUSBHC_PR2*2**2 + (CONFIG_GRUSBHC_PR1/4)

#define CONFIG_GRUSBHC_PORTROUTE2 CONFIG_GRUSBHC_PR15*2**26 + CONFIG_GRUSBHC_PR14*2**22 +\
                                  CONFIG_GRUSBHC_PR13*2**18 + CONFIG_GRUSBHC_PR12*2**14 +\
                                  CONFIG_GRUSBHC_PR11*2**10 + CONFIG_GRUSBHC_PR10*2**6 +\
                                  CONFIG_GRUSBHC_PR9*2**2 + (CONFIG_GRUSBHC_PR1 mod 4) 


