#ifndef CONFIG_GRUSB_DCL
#define CONFIG_GRUSB_DCL 0
#endif

#if defined CONFIG_GRUSB_DCL_UTMI16
#define CONFIG_GRUSB_DCL_UIFACE 0
#define CONFIG_GRUSB_DCL_DW 16
#elif defined CONFIG_GRUSB_DCL_UTMI8
#define CONFIG_GRUSB_DCL_UIFACE 0
#define CONFIG_GRUSB_DCL_DW 8
#else
#define CONFIG_GRUSB_DCL_UIFACE 1
#define CONFIG_GRUSB_DCL_DW 8
#endif
