#ifndef CONFIG_GRUSBDC_ENABLE
#define CONFIG_GRUSBDC_ENABLE 0
#endif

#ifndef CONFIG_GRUSBDC_AIFACE
#define CONFIG_GRUSBDC_AIFACE 0
#endif

#if defined CONFIG_GRUSBDC_UTMI16
#define CONFIG_GRUSBDC_UIFACE 0
#define CONFIG_GRUSBDC_DW 16
#elif defined CONFIG_GRUSBDC_UTMI8
#define CONFIG_GRUSBDC_UIFACE 0
#define CONFIG_GRUSBDC_DW 8
#else
#define CONFIG_GRUSBDC_UIFACE 1
#define CONFIG_GRUSBDC_DW 8
#endif

#ifndef CONFIG_GRUSBDC_NEPI
#define CONFIG_GRUSBDC_NEPI 1
#endif

#ifndef CONFIG_GRUSBDC_NEPO
#define CONFIG_GRUSBDC_NEPO 1
#endif

#ifndef CONFIG_GRUSBDC_I0
#define CONFIG_GRUSBDC_I0 1024
#endif
#ifndef CONFIG_GRUSBDC_I1
#define CONFIG_GRUSBDC_I1 1024
#endif
#ifndef CONFIG_GRUSBDC_I2
#define CONFIG_GRUSBDC_I2 1024
#endif
#ifndef CONFIG_GRUSBDC_I3
#define CONFIG_GRUSBDC_I3 1024
#endif
#ifndef CONFIG_GRUSBDC_I4
#define CONFIG_GRUSBDC_I4 1024
#endif
#ifndef CONFIG_GRUSBDC_I5
#define CONFIG_GRUSBDC_I5 1024
#endif
#ifndef CONFIG_GRUSBDC_I6
#define CONFIG_GRUSBDC_I6 1024
#endif
#ifndef CONFIG_GRUSBDC_I7
#define CONFIG_GRUSBDC_I7 1024
#endif
#ifndef CONFIG_GRUSBDC_I8
#define CONFIG_GRUSBDC_I8 1024
#endif
#ifndef CONFIG_GRUSBDC_I9
#define CONFIG_GRUSBDC_I9 1024
#endif
#ifndef CONFIG_GRUSBDC_I10
#define CONFIG_GRUSBDC_I10 1024
#endif
#ifndef CONFIG_GRUSBDC_I11
#define CONFIG_GRUSBDC_I11 1024
#endif
#ifndef CONFIG_GRUSBDC_I12
#define CONFIG_GRUSBDC_I12 1024
#endif
#ifndef CONFIG_GRUSBDC_I13
#define CONFIG_GRUSBDC_I13 1024
#endif
#ifndef CONFIG_GRUSBDC_I14
#define CONFIG_GRUSBDC_I14 1024
#endif
#ifndef CONFIG_GRUSBDC_I15
#define CONFIG_GRUSBDC_I15 1024
#endif
#ifndef CONFIG_GRUSBDC_O0
#define CONFIG_GRUSBDC_O0 1024
#endif
#ifndef CONFIG_GRUSBDC_O1
#define CONFIG_GRUSBDC_O1 1024
#endif
#ifndef CONFIG_GRUSBDC_O2
#define CONFIG_GRUSBDC_O2 1024
#endif
#ifndef CONFIG_GRUSBDC_O3
#define CONFIG_GRUSBDC_O3 1024
#endif
#ifndef CONFIG_GRUSBDC_O4
#define CONFIG_GRUSBDC_O4 1024
#endif
#ifndef CONFIG_GRUSBDC_O5
#define CONFIG_GRUSBDC_O5 1024
#endif
#ifndef CONFIG_GRUSBDC_O6
#define CONFIG_GRUSBDC_O6 1024
#endif
#ifndef CONFIG_GRUSBDC_O7
#define CONFIG_GRUSBDC_O7 1024
#endif
#ifndef CONFIG_GRUSBDC_O8
#define CONFIG_GRUSBDC_O8 1024
#endif
#ifndef CONFIG_GRUSBDC_O9
#define CONFIG_GRUSBDC_O9 1024
#endif
#ifndef CONFIG_GRUSBDC_O10
#define CONFIG_GRUSBDC_O10 1024
#endif
#ifndef CONFIG_GRUSBDC_O11
#define CONFIG_GRUSBDC_O11 1024
#endif
#ifndef CONFIG_GRUSBDC_O12
#define CONFIG_GRUSBDC_O12 1024
#endif
#ifndef CONFIG_GRUSBDC_O13
#define CONFIG_GRUSBDC_O13 1024
#endif
#ifndef CONFIG_GRUSBDC_O14
#define CONFIG_GRUSBDC_O14 1024
#endif
#ifndef CONFIG_GRUSBDC_O15
#define CONFIG_GRUSBDC_O15 1024
#endif
