; $Id: test_0050_iword.mac 502 2013-04-02 19:29:30Z mueller $
;
; test implicit .word
;   when a statement does not start with pst symbol (opcode or directive)
;   assume an implicit .word
; 
        .asect
        .blkw   400
         
        100                     ;;!! 000100
        200                     ;;!! 000200
        110,120                 ;;!! 000110 000120
        100,                    ;;!! 000100 000000
        ,200                    ;;!! 000000 000200
        ,                       ;;!! 000000 000000

w1:     1000                    ;;!! 001000
w2:     2000,2001,2002          ;;!! 002000 002001 002002

        const = 10              ;;!! 000010
        const                   ;;!! 000010
        <const>                 ;;!! 000010
        2*const                 ;;!! 000020
        <3*const>               ;;!! 000030

        .even
        .end
