; $Id: test_0120_op_rg.mac 575 2014-07-27 20:55:41Z mueller $
;
; test opcodes with 1 1/2 operands
;
        .asect
        .blkw   400 

a:      .word   0
pa:     .word   a

sub:    rts     pc              ;;!! 001004: 000207
        jsr     pc,sub          ;;!! 001006: 004767 177772

        xor     r1,a            ;;!! 074167 177762 

        mul     a,r2            ;;!! 070267 177756
        div     @pa,r2          ;;!! 071277 177754
        ash     #12,r3          ;;!! 072327 000012
        ashc    @#a,r4          ;;!! 073437 001000

; test call + return aliases too
sub1:   return                  ;;!! 000207
        call    sub1            ;;!! 004767 177772

        .end
