; $Id: test_0200_fpp_1op.mac 501 2013-03-30 13:53:39Z mueller $
;
; test fpp opcodes with 0 or 1 operands
;
        .asect
        .blkw   400 

a:      .word   0,0
        .word   0,0
pa:     .word   a
s:      .word   0,0
ps:     .word   s

; 0 operand opcodes

        cfcc                    ;;!! 170000
        setf                    ;;!! 170001
        setd                    ;;!! 170011
        seti                    ;;!! 170002
        setl                    ;;!! 170012

; 1 operand opcodes

        ldfps   s               ;;!! 170167 177754
        stfps   @#s             ;;!! 170237 001012
        stst    @ps             ;;!! 170377 177750
        clrf    r0              ;;!! 170400
        clrd    @r1             ;;!! 170411
        tstf    (r2)+           ;;!! 170522
        tstd    @(r3)+          ;;!! 170533
        absf    -(r4)           ;;!! 170644
        absd    @-(r5)          ;;!! 170655
        negf    a(r1)           ;;!! 170761 001000
        negd    @pa(r2)         ;;!! 170772 001010

        .end
