; $Id: test_0140_op_o.mac 501 2013-03-30 13:53:39Z mueller $
;
; test opcodes offset operands
;
        .asect
        .blkw   400 

; branch

start:  br      start
        bne     start
        beq     start
        bge     2$
        blt     2$
        bgt     2$
1$:     ble     2$

2$:     bpl     1$
        bmi     1$
        bhi     1$
        blos    1$
        bvc     1$
        bvs     1$
        bcc     1$
        bhis    3$
        bcs     3$
3$:     blo     3$

; sob

loop:   sob     r1,loop
        sob     r2,loop

        .end
