; $Id: test_0210_fpp_2op.mac 503 2013-04-06 19:44:13Z mueller $
;
; test fpp opcodes with 2 operands
;
        .asect
        .blkw   400 

a:      .word   0,0
        .word   0,0
pa:     .word   a
s:      .word   0,0
ps:     .word   s

; 2 operand 'gr' opcodes

        mulf    a,r0            ;;!! 171067 177754
        muld    r5,r1           ;;!! 171105
        modf    @r1,r2          ;;!! 171611
        modd    (r2)+,r3        ;;!! 171722
        addf    @(r3)+,r0       ;;!! 172033
        addd    -(r4),r1        ;;!! 172144
        ldf     @-(r5),r2       ;;!! 172655
        ldd     a,r3            ;;!! 172767 177734
        subf    @pa,r0          ;;!! 173077 177740
        subd    0(r1),r1        ;;!! 173161 000000
        cmpf    @6(r4),r2       ;;!! 173674 000006
        cmpd    r1,r3           ;;!! 173701
        divf    @pa,r0          ;;!! 174477 177722
        divd    r5,r1           ;;!! 174505

        ldexp   @r1,r0          ;;!! 176411
        ldcif   (r2)+,r1        ;;!! 177122
        ldcid   @(r2)+,r2       ;;!! 177232
        ldclf   -(r3),r3        ;;!! 177343
        ldcld   @-(r4),r0       ;;!! 177054
        ldcdf   a,r1            ;;!! 177567 177672
        ldcfd   @pa,r2          ;;!! 177677 177676

; 2 operand 'rg' opcodes

        stf     r0,a            ;;!! 174067 177662
        std     r1,@pa          ;;!! 174177 177666
        stexp   r2,@ps          ;;!! 175277 177670
        stcfi   r3,(r1)         ;;!! 175711
        stcfl   r0,(r2)+        ;;!! 175422
        stcdi   r1,@(r3)+       ;;!! 175533
        stcdl   r2,-(r4)        ;;!! 175644
        stcfd   r3,@-(r4)       ;;!! 176354
        stcdf   r0,@pa          ;;!! 176077 177644

        .end
