; $Id: test_0010_alloc.mac 501 2013-03-30 13:53:39Z mueller $
;
; test basic label and allocation constructs
;   .blkb
;   .blkw
;   .word
;   .byte
;   .even
;   .odd
;   normal and local labels
; 
; .blkb and .blkw
; 

        .asect

zero:                           ;;!! 000000:
        .blkb   1000
stkbot: .blkw   400             ;;!! 001000:

; .word and .byte
         
w0:     .word   101             ;;!! 002000: 000101
w1:     .word   102             ;;!! 002002: 000102
b0:     .byte   1               ;;!! 002004: 001
b1:     .byte   2               ;;!! 002005: 002

; .odd and .even     

        .odd
        .byte   3               ;;!! 002007: 003
        .byte   4               ;;!! 002010: 004
        .even
        .word   103             ;;!! 002012: 000103

; normal and local labels (only backward refs)
 
blk0:   .word   0               ;;!! 002014: 000000
1$:     .word   blk0            ;;!! 002016: 002014
2$:     .word   1$
3$:     .word   2$
;
blk1:   .word   0
1$:     .word   blk1
2$:     .word   1$
3$:     .word   2$

        .end                    ;;!! 000001
