; $Id: test_0040_asci.mac 548 2014-01-12 09:48:47Z mueller $
;
; test .ascii/.asciz
; 
        CR = 015
        LF = 012
;
        .asect
        .blkw   400
         
        .ascii  /foobar/        ;;!! 001000:
        .asciz  /fooba/         ;;!! 001006:

a0:     .ascii  /test/          ;;!! 001014:
a1:     .asciz  /test1/         ;;!! 001020:

a2:     .ascii  <CR><LF>/test/  ;;!! 001026:
a3:     .asciz  /test/<CR><LF>  ;;!! 001034:

a4:     .asciz  <CR><LF>/retro/<CR><LF>|computing|
a5:     .ascii  /Hello World!/
a6:     .asciz  *Hello World!*<CR><LF>
a7:     .asciz  <040><041><042>

        .even
        .end
