; $Id: test_0100_op_g.mac 501 2013-03-30 13:53:39Z mueller $
;
; test opcodes with one general operand
;
        .asect
        .blkw   400 
;
a:      .word   0               ;;!! 001000: 000000
pa:     .word   a               ;;!! 001002: 001000

; all modes with one opcode
p1:
        inc     r1              ;;!! 005201
        inc     @r2             ;;!! 005212
        inc     (r3)            ;;!! 005213
        inc     (r4)+           ;;!! 005224
        inc     @(r5)+          ;;!! 005235
        inc     -(r1)           ;;!! 005241
        inc     @-(r2)          ;;!! 005252
        inc     1234(r3)        ;;!! 005263 001234
        inc     @1234(r4)       ;;!! 005274 001234
        inc     a               ;;!! 005267 177742
        inc     @pa             ;;!! 005277 177740
        inc     @#a             ;;!! 005237 001000

; pc relative addressing

b:      .word   0
        inc     b
        inc     c
c:      .word   0

; all 'g' type opcodes, random modes
p2:
        jmp     @r2             ;;!! 000112
        swab    (r3)            ;;!! 000313
        clr     (r4)+           ;;!! 005024
        com     @(r5)+          ;;!! 005135
        dec     -(r1)           ;;!! 005341
        neg     @-(r2)          ;;!! 005452
        adc     1234(r3)        ;;!! 005563 001234
        sbc     @1234(r4)       ;;!! 005674 001234
        tst     a               ;;!! 005767 177666
        ror     @pa             ;;!! 006077 177664
        rol     @#a             ;;!! 006137 001000
        asr     @r2             ;;!! 006212
        asl     (r3)            ;;!! 006313
        mfpi    (r4)+           ;;!! 006524
        mtpi    @(r5)+          ;;!! 006635
        sxt     -(r1)           ;;!! 006741
;       csm     @-(r2)          ;;!! 
;       tstset  1234(r3)        ;;!! 
;       wrtlck  @1234(r4)       ;;!! 
        clrb    a               ;;!! 105067 177640
        comb    @pa             ;;!! 105177 177636
        incb    @#a             ;;!! 105237 001000
        decb    @r2             ;;!! 105312
        negb    (r3)            ;;!! 105413
        adcb    (r4)+           ;;!! 105524
        sbcb    @(r5)+          ;;!! 105635
        tstb    -(r1)           ;;!! 105741
        rorb    @-(r2)          ;;!! 106052
        rolb    1234(r3)        ;;!! 106163 001234
        asrb     @1234(r4)      ;;!! 106274 001234
        aslb    a               ;;!! 106367 177600
        mtps    @pa             ;;!! 106477 177576
        mfpd    @#a             ;;!! 106537 001000
        mtpd    @r2             ;;!! 106612
        mfps    (r3)            ;;!! 106713

        .end
