; $Id: test_0130_op_n.mac 501 2013-03-30 13:53:39Z mueller $
;
; test opcodes with no or numeric operands
;
        .asect
        .blkw   400 

; no operands
p1:
        halt                    ;;!! 000000
        wait                    ;;!! 000001
        rti                     ;;!! 000002
        bpt                     ;;!! 000003
        iot                     ;;!! 000004
        reset                   ;;!! 000005
        rtt                     ;;!! 000006
        mfpt                    ;;!! 000007
        nop                     ;;!! 000240
        clc                     ;;!! 000241
        clv                     ;;!! 000242
        clz                     ;;!! 000244
        cln                     ;;!! 000250
        sec                     ;;!! 000261
        sev                     ;;!! 000262
        sez                     ;;!! 000264
        sen                     ;;!! 000270
        scc                     ;;!! 000277
        
; numeric operands
p2:
        spl     5               ;;!! 000235
        mark    13              ;;!! 006413
        emt     170             ;;!! 104170
        trap    77              ;;!! 104477

        .end
