; $Id: zbug_0001.mac 501 2013-03-30 13:53:39Z mueller $
;
; ISSUE: .ascii without label failed with Q
; 
; REASON: .ascii requests next token with a different mask. The label handling
;   in state 'start' looks ahead with default mask and does a pushback. 
;   --> That clashed !!
;
; FIX: look to directive names in 'start' and branch to 'oper' immediately in
;   this case.
;
; SIDES: prevents also creation of labels with the name of a directive.
;
        .asect
        .blkw   400
        
        .word   0

a1:     .ascii  /test/
        .ascii  /test/          ; failed with Q
a2:     .ascii  /test/

        .end
