; $Id: zbug_0003.mac 502 2013-04-02 19:29:30Z mueller $
;
; for asm-11 prior rev 502
;
; ISSUE: '-2(r0)','@-2(r0) and '-sym(r0)',@-sym(r0) gives Q error
;
; REASON: confused in parser with '-(r0)' and '@-(r0)' modes
;
        .asect
        .blkw   400

        mov     -2(r0),r5
        mov     @-2(r0),r5
        mov     r5,-2(r0)
        mov     r5,@-2(r0)

        off = 2
        mov    -off(r0),r5 
        mov     @-off(r0),r5
        mov     r5,-off(r0)
        mov     r5,@-off(r0)

        .end
