#ifndef CONFIG_I2CSLV_ENABLE
#define CONFIG_I2CSLV_ENABLE 0
#endif

#ifndef CONFIG_I2CSLV_HARDADDR
#define CONFIG_I2CSLV_HARDADDR 0
#endif

#ifndef CONFIG_I2CSLV_TENBIT
#define CONFIG_I2CSLV_TENBIT 0
#endif

#ifndef CONFIG_I2CSLV_I2CADDR
#define CONFIG_I2CSLV_I2CADDR 0
#endif

