#ifndef CONFIG_SPICTRL_ENABLE
#define CONFIG_SPICTRL_ENABLE 0
#endif
#ifndef CONFIG_SPICTRL_SLVS
#define CONFIG_SPICTRL_SLVS 1
#endif
#ifndef CONFIG_SPICTRL_FIFO
#define CONFIG_SPICTRL_FIFO 1
#endif
#ifndef CONFIG_SPICTRL_SLVREG
#define CONFIG_SPICTRL_SLVREG 0
#endif
