#
# Makefile for FPGA implementations of ECO32
#

BUILD = ../build

.PHONY:		all install clean

all:
		$(MAKE) -C boards all

install:
		$(MAKE) -C boards install

clean:
		$(MAKE) -C boards clean
		rm -f *~
