

# Inherit global environment
Import('env')

# The set of source files associated with this SConscript file.
src_local = ['print-early.c','platform.c', 'irq.c']

obj = env.Object(src_local)
Return('obj')
