ifneq ($(CONFIG_ARCH_MV78XX0)$(CONFIG_ARCH_FEROCEON_MV78XX0),)
mcomm_mv78xx0-objs := mv78xx0.o
obj-m += mcomm_mv78xx0.o
endif

ifneq ($(CONFIG_PPC_85xx),)
mcomm_mpc85xx-objs := mpc85xx.o
obj-m += mcomm_mpc85xx.o
endif

mcomm_loop-objs := loop.o
mcomm-objs := common.o compat_anon_inodes.o

obj-m += mcomm.o mcomm_dev.o mcomm_loop.o

