#########################
# configuration section #
#########################

ZTEXPREFIX=../../..

JARTARGET=FlashDemo.jar
CLASSTARGETS=FlashDemo.class
CLASSEXTRADEPS=

IHXTARGETS=flashdemo.ihx
IHXEXTRADEPS=
EXTRAJARFILES=flashdemo.ihx
EXTRADISTCLEANFILES=

default: all

################################
# DO NOT CHANAGE THE FOLLOWING #
################################

include $(ZTEXPREFIX)/Makefile.mk

