
#ifndef __SYSCALL_H
#define __SYSCALL_H

enum SYS_COMMAND {
// SYS
	SYS_INIT,
// TIMER
	SYS_TIMER_INIT,
	SYS_TIMER_GET_COUNT,
// DMA
	SYS_DMA_INIT,
	SYS_DMA_ADD,
	SYS_DMA_ADD_FULL,
	SYS_DMA_GET_HANDLE,
	SYS_DMA_GET_CH,
// VRAM
	SYS_VRAM_INIT,
	SYS_VRAM_CLEAR,
	SYS_VRAM_IMAGE_PASTE,
	SYS_VRAM_IMAGE_PASTE_FILTER,
	SYS_VRAM_IMAGE_CLEAR,
// SCREEN
	SYS_SCREEN_INIT,
	SYS_SCREEN_CLEAR,
	SYS_SCREEN_LOCATE,
	SYS_SCREEN_SCROLL,
	SYS_SCREEN_PUT_STRING,
	SYS_SCREEN_PUT_CHAR,
	SYS_SCREEN_PRINT,
	//SYS_SCREEN_IMAGE,
	SYS_SCREEN_SET_LOCATE_X,
	SYS_SCREEN_SET_LOCATE_Y,
	SYS_SCREEN_GET_LOCATE_X,
	SYS_SCREEN_GET_LOCATE_Y,
	SYS_SCREEN_SET_COLOR_FG,
	SYS_SCREEN_SET_COLOR_BG,
// UART
	SYS_UART_INIT,
	SYS_UART_GET,
	SYS_UART_GET_EXIST,
	SYS_UART_GET_CLEAR,
	SYS_UART_PUT,
	SYS_UART_PUT_FULL,
	SYS_UART_PUT_CLEAR,
	SYS_UART_PUT_STRING,
	SYS_UART_IS_CTS,
	SYS_UART_IS_DSR,
	SYS_UART_IS_RI,
	SYS_UART_IS_DCD,
	SYS_UART_DTR,
	SYS_UART_RTS
};

long int			syscall(unsigned long int command,...)					__attribute__ ((section(".text")));

#endif
