
# Inherit global environment
import os, sys, glob

PROJRELROOT = '../../'

sys.path.append(PROJRELROOT)

from config.projpaths import *
from configure import *

Import('env', 'symbols')

# The set of source files associated with this SConscript file.
src_local = ['init.c', 'memory.c', 'systable.c', 'irq.c', 'cache.c', 'debug.c']

for name, val in symbols:
    if 'CONFIG_SMP' == name:
	src_local += ['smp.c', 'ipi.c']

obj = env.Object(src_local)
Return('obj')
