#############################################################################
# Syntheis constants
SYNCLEAN= SysTop.bgn SysTop.drc SysTop.mrp SysTop.ngd SysTop.pcf 
SYNCLEAN+= SysTop.bld SysTop.lso SysTop.ncd SysTop.ngm SysTop.srp 
SYNCLEAN+= SysTop.bit SysTop_signalbrowser.* SysTop-routed_pad.tx 
SYNCLEAN+= SysTop.map SysTop_summary.xml timing.twr
SYNCLEAN+= SysTop-routed* SysTop_usage* SysTop.ngc param.opt netlist.lst
SYNCLEAN+= *.log *_log

clean:
	rm -Rf $(SYNCLEAN) 
