SHELL=/bin/sh
MAKE=make
CUR_DIR=$(shell pwd)
home=$(CUR_DIR)/..

all:   install


.PHONY install:
install:
	(\
	chmod 755 ../../bin/* ;\
	chmod 755 ../../sys/* ;\
        sudo apt-get  install -y subversion;\
        sudo apt-get  install -y cvs;\
        sudo apt-get  install -y git;\
	sudo apt-get  install -y k3b;\
	sudo apt-get  install -y geda;\
	sudo apt-get  install -y emacs;\
	sudo apt-get  install -y seamonkey;\
        sudo apt-get  install -y libverilog-perl;\
	sudo apt-get  install -y libxml-libxml-perl;\
        sudo apt-get  install -y iverilog;\
        sudo apt-get  install -y covered;\
	sudo apt-get  install -y xutils-dev;\
        sudo apt-get  install -y gputils;\
	sudo apt-get  install -y gtkterm;\
	sudo apt-get  install -y gtkwave;\
	sudo apt-get  install -y perl-tk;\
	sudo apt-get  install -y perl-doc;\
	sudo apt-get  install -y texinfo;\
	sudo apt-get  install -y libncurses5-dev;\
	sudo apt-get  install -y build-essential;\
	sudo apt-get  install -y tkdiff;\
	sudo apt-get  install -y librxtx-java;\
	sudo apt-get  install -y libmpc2;\
	sudo apt-get  install -y verilator;\
	sudo apt-get  install -y crasm;\
	sudo apt-get  install -y xa65;\
	sudo apt-get  install -y texlive;\
	sudo apt-get  install -y asciidoc;\
	sudo apt-get  install -y bison;\
	sudo apt-get  install -y flex;\
	sudo apt-get  install -y gperf;\
	sudo apt-get  install -y sdcc;\
	sudo apt-get  install -y ghdl;\
	sudo apt-get  install -y csh;\
	sudo apt-get  install -y zlibc;\
	sudo apt-get  install -y zlib1g-dev;\
	sudo apt-get  install -y libx11-dev;\
	sudo apt-get  install -y gitk;\
	sudo apt-get  install -y git-gui;\
	sudo apt-get  install -y git-doc;\
	sudo apt-get  install -y git-core;\
	sudo apt-get  install -y gcc-4.4;\
	sudo apt-get  install -y texinfo;\
	sudo apt-get  install -y patch;\
	sudo apt-get  install -y libncurses5-dev;\
	sudo apt-get  install -y libusb-dev;\
	sudo apt-get  install -y libreadline6-dev;\
	sudo apt-get  install -y tex-info;\
	sudo apt-get  install -y texlive;\
	sudo apt-get  install -y libxml-simple-perl;\
	sudo apt-get  install -y autoconf;\
	sudo apt-get  install -y autopoint;\
	sudo apt-get  install -y libtool;\
	sudo apt-get  install -y qt4-qmake;\
	sudo apt-get  install -y qt4-designer;\
	sudo apt-get  install -y virtualbox-qt;\
	sudo apt-get  install -y quilt;\
	)


