#########################
# configuration section #
#########################

# Defines the location of the EZ-USB SDK
ZTEXPREFIX=../../../..

# The name of the jar archive
JARTARGET=MemFifo.jar
# Java Classes that have to be build 
CLASSTARGETS=MemFifo.class
# Extra dependencies for Java Classes
CLASSEXTRADEPS=

# ihx files (firmware ROM files) that have to be build 
IHXTARGETS=memfifo.ihx
# Extra Dependencies for ihx files
IHXEXTRADEPS=

# Extra files that should be included into th jar archive
EXTRAJARFILES=memfifo.ihx fpga/memfifo.runs/impl_1/memfifo.bit

################################
# DO NOT CHANAGE THE FOLLOWING #
################################
# includes the main Makefile
include $(ZTEXPREFIX)/Makefile.mk
