#!/bin/sh

	rm -Rf ram/*.mif
	rm -Rf ../simulation/modelsim/sw/ram/*.mif
	cd mpsoc_code
for i in $(ls *.c); do
        echo item: $i
	cp $i	../compile/code.c
	cd ../compile
	./gccrom	code.c
	cp	out/ram0.mif	../ram/${i%.*}.mif
	cp	out/ram0.mif	../../simulation/modelsim/sw/ram/${i%.*}.mif
	rm	code.c	
        cd ../mpsoc_code
done
