#########################
# configuration section #
#########################

ZTEXPREFIX=../..

JARTARGET=Default.jar
CLASSTARGETS=Default.class
CLASSEXTRADEPS=

IHXTARGETS=default.ihx
IHXEXTRADEPS=
EXTRAJARFILES=default.ihx
EXTRADISTCLEANFILES=

default: all

################################
# DO NOT CHANAGE THE FOLLOWING #
################################

include $(ZTEXPREFIX)/Makefile.mk

