.TH L4_TIME 7 2009-11-07 "Codezero" "Codezero Programmer's Manual"
.SH NAME
.nf
.BR "l4_time" " - sets or reads system time."

.SH SYNOPSIS
.nf
.B #include <l4lib/arch/syscalls.h>
.B #include <l4lib/arch/syslib.h>

.BI "int l4_time(struct timeval *" "timeval" ", int " "set" ");"

.SH DESCRIPTION
.BR "l4_time() " "sets or reads system time. "

.IR "timeval " "field is the representation of time since the system has started running. See below for details."

.IR "set " " field instructs whether the time is to be read or set to the values specified in the " "timeval " "field supplied."

.nf
.B struct timeval {
.BI "      int " "tv_sec;"  "    /* Time value in seconds */ "
.BI "      int " "tv_usec;" "   /* Time value in microseconds */ "
.B };
.fi

.SH LIMITATIONS
- Currently setting the time feature is disabled.

- Currently the system time is returned since the system has started rather than a set date.

- Currently this system call is not subject to capabilities.

.SH ERRORS
.TP
.B -EFAULT
.IR "timeval " "field would cause an unhandled page fault."
.TP
.B -EBUSY
Timer structures in the system are currently being used.
.TP
.B -ENOSYS
Operation of given type is not supported.

