.TH L4_THREAD_SWITCH 7 2009-11-02 "Codezero" "Codezero Programmer's Manual"
.SH NAME
.nf
.BR "l4_thread_switch" " - Yields the CPU"

.SH SYNOPSIS
.nf
.B #include <l4lib/arch/syscalls.h>
.B #include <l4lib/arch/syslib.h>

.BI "int l4_thread_switch(u32 " "dest" ");"
.SH DESCRIPTION
.BR l4_thread_switch()  " - yields the CPU. Current thread yields the CPU donating its left timeslice to thread with id specified in the
.I dest
field.

.SH RETURN VALUE
Always succeeds with a return value of 0.

