#!/usr/bin/env python

def build(bld):
	sources = [
		'create_svc.c',
		'destroy_svc.c',
		'reg_svcs.c',
		'linux/os_%s_demo.c' % bld.env.OS,
	]

	includes = [
		'..',
		bld.env.OS,
		'../../include',
		'../../include/%s' % bld.env.OS,
		'../../libmcapi/include',
	]

	bld.stlib(
		target='test_support',
		source=' '.join(sources),

		includes=' '.join(includes),
		cflags='-O2 -Wall',
	)
