Import('env', 'platform')

#Platforms using omap_uart
plat_list = 'beagle'

# The set of source files associated with this SConscript file.
src_local = []

#for plat_supported in plat_list:
#if plat_supported == platform:
if plat_list == platform:
    src_local += ['uart.c']

obj = env.StaticObject(src_local)
Return('obj')
