#!/bin/csh -f
#
#  This files analysis the log files and generat the regression status
#

echo "###########################################"
echo "  Analysis the Regression Status"
echo "############################################"
set failedm = 0; 
set all_testsm = 0;

set sdr_tests =( top_SDR_8BIT_basic_test1 top_SDR_16BIT_basic_test1 top_SDR_32BIT_basic_test1 core_SDR_8BIT_basic_test1 core_SDR_16BIT_basic_test1 core_SDR_32BIT_basic_test1)
#set misc_tests=( )


set i = 0;
        echo "###########################################"
foreach run_test ($sdr_tests)
	@ i += 1;
	if (`tail ../log/${run_test}.log | grep PASSED` == "") then
	  echo "### test ${i}: ${run_test} --> FAILED"
          @ failedm += 1;
          @ all_testsm += 1;
        else
	  echo "### test ${i}: ${run_test} --> PASSED"
          @ all_testsm += 1;
	endif
end
    echo "###########################################"


set i = 0;
echo ""
echo "###########################################"
echo "###  Test Logs                            "
foreach run_test ($sdr_tests)
	  @ i += 1;
	  echo "   test ${i}: ../log/${run_test}.log"

end
    echo "###########################################"


echo ""
echo "###########################################"
echo "###  Test Summary                          "
echo "### "
echo "### Failed $failedm of $all_testsm tests"
echo "###########################################"

