#!/bin/bash


if [ -z "$2" ] ; then
  DEVICE=3
else 
  DEVICE=$2
fi

echo "setMode -bscan" > /tmp/usbdownload
echo "setCable -p auto" >> /tmp/usbdownload
echo "identify" >> /tmp/usbdownload
echo "assignfile -p $DEVICE -file $1" >> /tmp/usbdownload
echo "program -p $DEVICE" >> /tmp/usbdownload
echo "quit" >> /tmp/usbdownload

. /opt/xilinx/8.2i/settings.sh
impact -batch < /tmp/usbdownload

rm /tmp/usbdownload

# clean up impact's mess
rm _impactbatch.log _impact.cmd

