#!/bin/bash
# Usage: xmddownload <file> <address>
#        xmddownload <file> 


if [ -z "$2" ] ; then
  ADDRESS=0x0
else
  ADDRESS=$2
fi

echo "connect ppc hw" > /tmp/xmddownload
echo "dow -data $1 $ADDRESS" >> /tmp/xmddownload
echo "con" >> /tmp/xmddownload
echo "disconnect ppc" >> /tmp/xmddownload
echo "exit" >> /tmp/xmddownload

xmd < /tmp/xmddownload

rm /tmp/xmddownload

