#!/bin/bash
#
# Copyright 2012, Sinclair R.F., Inc.
#
# Run all of the test benches for the peripherals.

for runname in `find -name run`; do
  cd  ${runname:0:${#runname}-4};
  ./run || { echo "Tests aborted at ${runname}"; exit 1; }
  cd ..
done

echo "All tests passed!";
exit 0;
