#########################
# configuration section #
#########################

ZTEXPREFIX=../../../..

JARTARGET=Lightshow.jar
CLASSTARGETS=Lightshow.class
CLASSEXTRADEPS=
#CLASSEXTRADEPS:=$(wildcard $(ZTEXPREFIX)/java/ztex/*.java)

IHXTARGETS=lightshow.ihx
IHXEXTRADEPS=
#IHXEXTRADEPS:=$(wildcard $(ZTEXPREFIX)/include/*.h)
EXTRAJARFILES=lightshow.ihx avr/lightshow.ihx fpga/lightshow.bit

################################
# DO NOT CHANAGE THE FOLLOWING #
################################

include $(ZTEXPREFIX)/Makefile.mk
