.\"  -*- nroff -*-
.\"  $Id: console_starter.1 581 2014-08-10 21:48:46Z mueller $
.\"
.\" Copyright 2013-2014 by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
.\" 
.\" ------------------------------------------------------------------
.
.TH CONSOLE_STARTER 1 2010-07-09 "Retro Project" "Retro Project Manual"
.\" ------------------------------------------------------------------
.SH NAME
console_starter \- setup vt52/vt100 emulator windows for ti_rri or simh
.\" ------------------------------------------------------------------
.SH SYNOPSIS
.
.SY console_starter
.OP \-t term
.OP \-d dev
.OP \-s
.OP \-w
.OP \-l
.
.SY console_starter
.B \-\-h
.YS
.
.\" ------------------------------------------------------------------
.SH DESCRIPTION
Script to setup a \fBxterm\fP vt52 or vt100 emulator window which
will connect to a DL11 or DZ11 serial interface emulation port of
\fBti_rri\fP or a CPU emulator from the \fBsimh\fP suite, 
e.g. \fBpdp11\fP, via a \fBtelnet\fP connection.

If the connect to the interface emulation port fails or is terminated
a message like

.EX
    localhost 8000
    Trying 127.0.0.1...
    telnet: Unable to connect to remote host: Connection refused
    telnet failed with rc=256
    enter q or <^D> to quit, otherwise hit <ENTER> to reconnect: 
.EE

is displayed in the \fBxterm\fP window. Entering a 'q' or 'Control-D'
will terminate the \fBxterm\fP window, after pressing the '<ENTER>'
key a re-connect will be tried.

.
.\" ------------------------------------------------------------------
.SH OPTIONS
.
.\" ----------------------------------------------
.IP "\fB\-t \fIterm\fR"
defines the terminal emulator type. Allowed values are:
.RS
.RS 3
.PD 0
.IP \fBvt100\fP 8
use VT100 emulation. The default.
.IP \fBvt52\fP
use VT52 emulation. Useful in conjunction with OS which do not have VT100
support, like early DEC RSX-11M versions.
.RE
.RE
.PD
.
.\" ----------------------------------------------
.IP "\fB\-d \fIdev\fR"
defines the serial interface emulation port to connect to. Supported
are currently primary and secondary DL11 interface and eight lines of
the first DZ11 interface. Allowed values for \fIdev\fP are:
.RS
.RS 3
.PD 0
.IP \fBDL0\fP 6
first DL11 (usually console). The default.
.IP \fBDL1\fP 6
second DL11.
.IP \fBDZ\fIn\fP 6
eight lines of the first DZ11. \fIn\fP = 0,...,7.
.RE
.RE
.PD
.
.\" ----------------------------------------------
.IP "\fB\-s\fR"
Use simh port numbers. Default is to use \fBti_rri\fP ports.
.
.\" ----------------------------------------------
.IP "\fB\-w\fR"
Use a wide 132 column screen. Default is 80 column screen width.
.
.\" ----------------------------------------------
.IP "\fB\-l\fR"
Use a long 48 line screen. Default is a 24 lines screen height.
.
.\" ----------------------------------------------
.IP "\fB\-h\fR"
print full help text and exit.
.
.
.\" ------------------------------------------------------------------
.SH EXIT STATUS
In case of an error an exit status 1 is returned.
.
.
.\" ------------------------------------------------------------------
.SH EXAMPLES
.IP "\fBconsole_starter -d DL0 &\fR" 4
Creates a background process with a \fBxterm\fP in VT100 emulation mode
with a 80x24 screen size which will try to connect to the primary DL11 
emulator port of \fBti_rri\fP.
.
.IP "\fBconsole_starter -t vt52 -d DL1 -s &\fR"
Creates a background process with a \fBxterm\fP in VT52 emulation mode
with a 80x24 screen size which will try to connect to the secondary DL11 
emulator port of a \fBsimh\fP suite CPU emulator.
.
.\" ------------------------------------------------------------------
.SH "SEE ALSO"
.BR telnet (1),
.BR ti_rri (1),
.BR xterm (1)

.\" ------------------------------------------------------------------
.SH AUTHOR
Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
