.\"  -*- nroff -*-
.\"  $Id: svn_set_ignore.1 550 2014-02-03 08:16:57Z mueller $
.\"
.\" Copyright 2013- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
.\" 
.\" ------------------------------------------------------------------
.
.TH SVN_SET_IGNORE 1 2010-04-26 "Retro Project" "Retro Project Manual"
.\" ------------------------------------------------------------------
.SH NAME
svn_set_ignore \- setup svn:ignore properties based on .cvsignore files
.\" ------------------------------------------------------------------
.SH SYNOPSIS
.
.SY svn_set_ignore
.OP \-\-dry-run
.YS
.
.\" ------------------------------------------------------------------
.SH DESCRIPTION
Creates or updates a \fIsvn:ignore\fP property for the current directory
and all sub-directories. The current directory must contain a
\fI.cvsignore\fP file which defines the default list of ignore patterns for the
whole project. If a local \fI.cvsignore\fP file is found in a sub directory
its content will be appended to the default list.
.
If no \fIsvn:ignore\fP property exists or the existing one differs from
the ignore pattern list determined from the top level and local 
\f.cvsignore\fP file the property is set or updated.
.
.\" ------------------------------------------------------------------
.SH OPTIONS
.
.\" ----------------------------------------------
.IP \fB\-\-dry-run\fP
Shows \fIsvn:ignore\fP property changes, but doesn't store them in the
svn repository.
.
.\" ------------------------------------------------------------------
.SH EXIT STATUS
If no  \fI.cvsignore\fP file is found or a \fBsvn\fP(1) command fails the 
script dies with exit status 2.
.
.\" ------------------------------------------------------------------
.SH "SEE ALSO"
.BR svn (1)

.\" ------------------------------------------------------------------
.SH AUTHOR
Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
