.\"  -*- nroff -*-
.\"  $Id: ti_w11.1 680 2015-05-14 13:29:46Z mueller $
.\"
.\" Copyright 2013-2015 by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
.\" 
.\" ------------------------------------------------------------------
.
.TH TI_W11 1 2015-04-12 "Retro Project" "Retro Project Manual"
.\" ------------------------------------------------------------------
.SH NAME
ti_w11 \- Quick starter for \fBti_rri\fP with \fBw11\fP CPU designs
.\" ------------------------------------------------------------------
.SH SYNOPSIS
.
.SY ti_w11
.OP OPTIONS
.OP "ti_rri options and commands"
.YS
.
.\" ------------------------------------------------------------------
.SH DESCRIPTION
Generates the \fBti_rri\fP(1) commands for starting the \fBrri\fP backend
in standard configurations with \fBw11\fP CPU designs. Connections to
FPGA boards as well as to \fPghdl\fP based simulations are supported.

Since \fBti_w11\fP is only a quick starter for \fBti_rri\fP(1) this man page
will only describe briefly the \fBti_w11\fP specific options, for any further
detail consult the \fBti_rri\fP(1) man page.

\fBti_w11\fP will print the generated \fBti_rri\fP(1) command to stdout before
executing it.
.
.\" ------------------------------------------------------------------
.SH OPTIONS
.SS "setup options for FPGA connects"
.IP \fB-u\fP
use \fB\-\-cuff\fP connect (USB via Cypress FX2)
.IP \fB-t\fIDN\fR[,\fIopts\fP]
use \fB\-\-term\fP connect, \fID\fP specifies device name, \fIN\fP
specified the device number, and \fIopts\fP the addtional options
a \fB\-\-term\fP can hold (e.g. break or xon). \fID\fP is mapped as
.RS
.PD 0
.IP \fBs\fP 4
use /dev/ttyS*  (* is device number \fIN\fP)
.IP \fBu\fP 4
use /dev/ttyUSB*  (* is device number \fIN\fP)
.PD
.RE
.
.SS "setup options for ghdl simulation runs"
.PD 0
.IP \fB-b3\fP
start \fItb_w11a_b3\fP simulation (w11a on Basys3, default \fB-f1x\fP)
.IP \fB-n4\fP
start \fItb_w11a_n4\fP simulation (w11a on Nexys4)
.IP \fB-n3\fP
start \fItb_w11a_n3\fP simulation (w11a on Nexys3, default \fB-fc\fP)
.IP \fB-n2\fP
start \fItb_w11a_n2\fP simulation (w11a on Nexys2, default \fB-fc\fP)
.IP \fB-s3\fP
start \fItb_w11a_s3\fP simulation (w11a on S3board, default \fB-f2\fP)
.PD
.IP \fB-f\fIm\fR
select communication mode for simulation. The \fB-f\fIm\fR can be used after
the \fB-b3\fP,...,\fB-s3\fP options to overwrite the default. Valid values 
for mode \fIm\fP are
.RS
.PD 0
.IP \fBc\fP 4
use Cypress FX2 data path (cuff, only for -n2 and -n3)
.IP \fB1\fP 4
use 1st serport
.IP \fB1x\fP 4
use 1st serport with xon
.IP \fB2\fP 4
use 2nd serport (fusp, only for -s3,-n2,-n3)
.IP \fB2x\fP 4
use 2nd serport with xon
.PD
.RE
.IP \fB-tmu\fP
activate trace and monitoring unit
.
.SS "common options"
.IP \fB-e "\fR=\fIfile"\fR
load and execute \fIfile\fP. If the file type is '.mac' the file will
be on the fly compiled with \fBasm-11\fP(1), for all other file types
it is assumed that they are in \fBlda\fP(5) format.
.
.\" ------------------------------------------------------------------
.SH EXAMPLES
.IP "\fBti_w11 -u @211bsd_rk_boot.tcl\fR" 4
Assumes a FPGA board with a \fBw11\fP CPU design already configured.
Connected via USB, communication via Cypress FX2.
\fBti_rri\fP(1) will be started and the given boot script executed.
Typical way to start Nexys2 and Nexys3 boards.

.IP "\fBti_w11 -tu2,10M,break,cts @211bsd_rl_boot.tcl\fR" 4
Assumes a FPGA board with a \fBw11\fP CPU design already configured.
Connected via USB, communication via an USB UART. In this case the
device \fI/dev/ttyUSB2\fP will be used, with \fI10 MBaud\fP, \fIbreak\fP to
trigger auto-bauding, and \fIcts\fP to use hardware handshake.
\fBti_rri\fP(1) will be started and the given boot script executed.
Typical way to start Nexys4 boards.

.IP "\fBti_w11 -n3 -e $RETROBASE/tools/asm-11/w11/sys/dl11/simple_out.mac\fR"
Will start the \fItb_w11a_n3\fP test bench in \fBghdl\fP(1), on the fly 
compile the \fIsimple_out.mac\fP test program with \fBasm-11\fP(1), load 
and execute it. This little test code just produces
.EX
   Hello world!
   Hello world!
.EE
forever, just abort with ^C if you have seen enough.
.
.\" ------------------------------------------------------------------
.SH "SEE ALSO"
.BR ti_rri (1),
.BR asm-11 (1)

.\" ------------------------------------------------------------------
.SH AUTHOR
Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
