.\"  -*- nroff -*-
.\"  $Id: xtwi.1 651 2015-02-26 21:32:15Z mueller $
.\"
.\" Copyright 2014- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
.\" 
.\" ------------------------------------------------------------------
.
.TH XTWI 1 2013-11-10 "Retro Project" "Retro Project Manual"
.\" ------------------------------------------------------------------
.SH NAME
xtwi \- Xilinx Tool Wrapper script for ISE
.\" ------------------------------------------------------------------
.SH SYNOPSIS
.
.SY xtwi 
.OP COMMAND
.YS
.
.\" ------------------------------------------------------------------
.SH DESCRIPTION
The Xilinx ISE setup script redefines PATH and LD_LIBRARY_PATH. The ISE
tools run fine in this environment, but other installed programs on the
system can (and actually do) fail. \fBxtwi\fP helps to keep the ISE 
environment separate from the normal working environment.

The environment variable XTWI_PATH must be setup to the install path 
of the ISE version to be used. Without the /ISE_DS/ which is added
by the ISE installation procedure.

\fBxtwi\fP uses XTWI_PATH to locate the ISE setup script, sources it, 
and execs the \fICOMMAND\fP. This way \fICOMMAND\fP is executed in the
ISE environment, while the login shell stays clean.

.
.\" ------------------------------------------------------------------
.SH ENVIRONMENT
.TP 4
.B XTWI_PATH
Install path of ISE, without the /ISE_DS/ appended by ISE installation 
.
.\" ------------------------------------------------------------------
.SH FILES
.TP 4
$XTWI_PATH/ISE_DS/settings32.sh
.TQ
$XTWI_PATH/ISE_DS/settings64.sh
ISE setup script located and sourced on 32 or 64 bit systems
.
.\" ------------------------------------------------------------------
.SH EXAMPLES
.IP "\fBxtwi netgen -sim  -intstyle xflow -ofmt vhdl -w test.ngc" 4
Starts the ISE netlister and generates a vhdl model from \fItest.ngc\fP.
.
.\" ------------------------------------------------------------------
.SH "NOTES"
If both ISE and Vivado are used \fBxtwi\fP and \fBxtwv\fP(1) offer a convenient
way to have both tools available in one session without interference.
.
.\" ------------------------------------------------------------------
.SH "SEE ALSO"
.BR xtwv (1)
.
.\" ------------------------------------------------------------------
.SH AUTHOR
Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
