#!/bin/bash
#
# Copyright 2013, Sinclair R.F., Inc.

NAME=big_inport

../../../../../ssbcc -q -P monitor_stack tb_${NAME}.9x8 || { echo "${NAME} compile failed" > /dev/stderr; exit 1; }
iverilog -o tb tb.v tb_${NAME}.v || { echo "${NAME} build failed" > /dev/stderr; exit 1; }
./tb > tb.out;

T="`md5sum -c md5sums 2>&1 | sed '/: OK$/d'`";
if [ -n "${T}" ]; then
  echo "${NAME} failed" > /dev/stderr;
  exit 1;
fi

echo "Passed:  ${NAME}";
exit 0;
