# -*- mode: python; coding: utf-8; -*-

#  Codezero -- a microkernel for embedded systems.
#
#  Copyright © 2009  B Labs Ltd
import os, sys

PROJRELROOT = '../..'

sys.path.append(PROJRELROOT)

from config.projpaths import *
from configure import *

Import('env')

LIBL4_RELDIR = 'conts/libl4'
LIBL4_DIR = join(PROJROOT, LIBL4_RELDIR)
LIBL4_INCLUDE = join(LIBL4_DIR, 'include')

e = env.Clone()
e.Append(CPPPATH = ['include', '.', LIBL4_INCLUDE])

objmm = e.StaticObject(Glob('mm/*.c'))
objmc = e.StaticObject(Glob('memcache/*.[cS]'))
objmalloc = e.StaticObject(Glob('malloc/*.[cS]'))
libmm = e.StaticLibrary('mm', objmm)
libmc = e.StaticLibrary('mc', objmc)
libmalloc = e.StaticLibrary('malloc', objmalloc)

Return('libmm', 'libmc', 'libmalloc')
