
#ifndef CONFIG_SPIMCTRL
#define CONFIG_SPIMCTRL 0
#endif

#ifndef CONFIG_SPIMCTRL_SDCARD
#define CONFIG_SPIMCTRL_SDCARD 0
#endif

#ifndef CONFIG_SPIMCTRL_READCMD
#define CONFIG_SPIMCTRL_READCMD 0
#endif

#ifndef CONFIG_SPIMCTRL_DUMMYBYTE
#define CONFIG_SPIMCTRL_DUMMYBYTE 0
#endif

#ifndef CONFIG_SPIMCTRL_DUALOUTPUT
#define CONFIG_SPIMCTRL_DUALOUTPUT 0
#endif

#ifndef CONFIG_SPIMCTRL_SCALER
#define CONFIG_SPIMCTRL_SCALER 1
#endif

#ifndef CONFIG_SPIMCTRL_ASCALER
#define CONFIG_SPIMCTRL_ASCALER 1
#endif

#ifndef CONFIG_SPIMCTRL_PWRUPCNT
#define CONFIG_SPIMCTRL_PWRUPCNT 0
#endif
