all: ../bin/out2rom-ml403 ../bin/ff

../bin/splitlh: splitlh.c
	gcc -o ../bin/splitlh splitlh.c
../bin/out2rom-ml403: out2rom-ml403.c
	gcc -o ../bin/out2rom-ml403 out2rom-ml403.c
../bin/ff: ff.c
	gcc -o ../bin/ff ff.c
